(function(){
const G=window.Game,base=String(window.NAIJA_API_BASE||'').replace(/\/$/,''),root=document.getElementById('account-auth'),form=document.getElementById('auth-form'),fields=document.getElementById('auth-fields'),msg=document.getElementById('auth-message'),submit=document.getElementById('auth-submit');
const A=G.auth={user:null,mode:'register',busy:false,ready:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opts={}){let r;try{r=await fetch(base+'/api'+path,{credentials:'include',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}})}catch{throw Error(base?'Could not reach the account server. Check the API URL and try again.':'Real accounts need the HTTPS Node account API, which is not connected to GitHub Pages yet.')}let d={};try{d=await r.json()}catch{}if(!r.ok){if(r.status===404||!Object.keys(d).length)throw Error('The account API is not connected. Host the Node backend over HTTPS and set NAIJA_API_BASE to its URL.');throw Error(d.error||'The account server could not complete this request.')}return d}
function setMessage(text,kind=''){msg.textContent=text;msg.className='auth-message '+kind}
function field(id,label,type,placeholder,attrs=''){return `<label for="auth-${id}">${label}<span class="auth-input-wrap"><input id="auth-${id}" name="${id}" type="${type}" placeholder="${placeholder}" ${attrs}></span></label>`}
function render(){const reset=new URLSearchParams(location.search).get('reset');if(reset){A.mode='reset';document.getElementById('auth-tab-register').hidden=true;document.getElementById('auth-tab-login').hidden=true;document.getElementById('auth-heading').textContent='Choose a new password';fields.innerHTML=`<p class="auth-description">Choose a new password for your account.</p>${field('password','New password','password','At least 12 characters','minlength="12" autocomplete="new-password" required')}${field('confirm','Confirm new password','password','Enter the password again','autocomplete="new-password" required')}`;submit.textContent='Save new password';document.getElementById('auth-footnote').textContent='Your reset link can only be used once.';document.getElementById('auth-link-row').innerHTML='<a href="?login">Back to log in</a>';return}
 document.getElementById('auth-tab-register').hidden=A.mode==='forgot';document.getElementById('auth-tab-login').hidden=A.mode==='forgot';document.getElementById('auth-tab-register').setAttribute('aria-selected',A.mode==='register');document.getElementById('auth-tab-login').setAttribute('aria-selected',A.mode==='login');document.getElementById('auth-heading').textContent=A.mode==='forgot'?'Forgot your password?':A.mode==='register'?'Create your Naija Life account':'Log in to Naija Life';
 if(A.mode==='forgot'){fields.innerHTML=`<h2>Forgot your password?</h2><p class="auth-description">Enter your email. If your account has one, we'll send you a link to choose a new password.</p>${field('email','Email address','email','you@email.com','autocomplete="email" required')}`;submit.textContent='Send reset link';document.getElementById('auth-footnote').textContent='';document.getElementById('auth-link-row').innerHTML='<a href="#" data-auth-mode="login">Back to log in</a>';return}
 if(A.mode==='register'){fields.innerHTML=`${field('name','Your name','text','e.g. Tolu Adebayo','maxlength="32" autocomplete="name" required')}${field('username','Username','text','@tolu_eko','minlength="3" maxlength="20" pattern="[A-Za-z0-9_]{3,20}" autocomplete="username" required')}<small class="auth-help">This is your Sim's name in Lagos Life.</small>${field('email','Email address','email','you@email.com','autocomplete="email" required')}${field('password','Password','password','At least 12 characters','minlength="12" autocomplete="new-password" required')}${field('confirm','Confirm password','password','Enter the password again','autocomplete="new-password" required')}<label class="auth-consent"><input id="auth-consent" type="checkbox" required><span>I'm <b>18 or older</b> and I agree to the <a href="terms.html" target="_blank">Terms</a> and <a href="privacy.html" target="_blank">Privacy Policy</a>.</span></label>`;submit.textContent='Sign up · it’s free';document.getElementById('auth-footnote').textContent='Your Sim will live in the same Lagos as everyone else who signs up.';document.getElementById('auth-link-row').innerHTML='Already have an account? <a href="#" data-auth-mode="login">Sign in</a>'}
 else{fields.innerHTML=`${field('identity','Username or email','text','tolu_eko or you@email.com','autocomplete="username" required')}${field('password','Password','password','Enter your password','autocomplete="current-password" required')}<a class="auth-forgot" href="#" data-auth-mode="forgot">Forgot password?</a>`;submit.textContent='Log in';document.getElementById('auth-footnote').textContent='Welcome back to Lagos.';document.getElementById('auth-link-row').innerHTML='New to Lagos? <a href="#" data-auth-mode="register">Create an account</a>'}
 fields.querySelectorAll('input[type=password]').forEach(input=>{const wrap=input.parentElement;const button=document.createElement('button');button.type='button';button.className='password-toggle';button.setAttribute('aria-label','Show password');button.textContent='◉';button.onclick=()=>{input.type=input.type==='password'?'text':'password';button.setAttribute('aria-label',input.type==='password'?'Show password':'Hide password')};wrap.append(button)});
}
function mode(m){A.mode=m;setMessage('');render()}
function setup(){root.hidden=true;document.getElementById('life-setup').hidden=false;document.getElementById('signed-in-label').textContent=location.protocol==='file:'?'LOCAL PREVIEW · no account connected':`Signed in as @${A.user.username||A.user.displayName}`;document.getElementById('name-input').value=A.user.displayName||A.user.username||'Amara';for(const key of ['gender','skin','hair','outfit'])if(A.user.avatar?.[key])document.getElementById(key).value=A.user.avatar[key];if(G.load()){document.getElementById('name-input').value=G.state.name;for(const key of ['gender','skin','hair','outfit'])document.getElementById(key).value=G.state[key]||document.getElementById(key).value;document.getElementById('continue-game').hidden=false}else document.getElementById('continue-game').hidden=true;G.creator?.open(A.user,!!G.load());if(location.protocol==='file:'){const exit=document.getElementById('creator-signout');if(exit)exit.textContent='Back to login'}}
G.authSaveAvatar=async()=>{const avatar=G.creator?.avatar?.()||Object.fromEntries(['gender','skin','hair','outfit'].map(key=>[key,document.getElementById(key).value]));if(location.protocol==='file:'){A.user.avatar=avatar;return}try{await api('/profile/avatar',{method:'PUT',body:JSON.stringify(avatar)});A.user.avatar=avatar}catch(e){G.toast('Your appearance could not sync to your account: '+e.message)}};
document.getElementById('auth-tab-register').onclick=()=>mode('register');document.getElementById('auth-tab-login').onclick=()=>mode('login');document.getElementById('auth-link-row').addEventListener('click',e=>{const a=e.target.closest('[data-auth-mode]');if(a){e.preventDefault();mode(a.dataset.authMode)}});
form.addEventListener('submit',async e=>{e.preventDefault();if(A.busy)return;if(!form.reportValidity())return;const val=id=>document.getElementById('auth-'+id)?.value||'';if(A.mode==='register'&&!document.getElementById('auth-consent')?.checked)return setMessage('Please confirm you are 18 or older and agree to the terms.','error');if(['register','reset'].includes(A.mode)&&val('password')!==val('confirm'))return setMessage('Those passwords do not match.','error');if(['register','reset'].includes(A.mode)&&val('password').length<12)return setMessage('Use at least 12 characters for your password.','error');A.busy=true;submit.disabled=true;submit.textContent='Please wait…';setMessage('');try{if(A.mode==='register'){await api('/auth/register',{method:'POST',body:JSON.stringify({email:val('email'),displayName:val('name'),username:val('username'),password:val('password'),adultConsent:true})});A.user=(await api('/auth/me')).user;setup()}else if(A.mode==='login'){await api('/auth/login',{method:'POST',body:JSON.stringify({identity:val('identity'),password:val('password')})});A.user=(await api('/auth/me')).user;setup()}else if(A.mode==='forgot'){await api('/auth/forgot-password',{method:'POST',body:JSON.stringify({email:val('email')})});setMessage('If an account matches that email, a reset link has been sent. Check your inbox.','success')}else if(A.mode==='reset'){await api('/auth/reset-password',{method:'POST',body:JSON.stringify({token:new URLSearchParams(location.search).get('reset'),password:val('password')})});history.replaceState(null,'',location.pathname);mode('login');setMessage('Password updated. You can now log in.','success')}}catch(error){setMessage(error.message,'error')}finally{A.busy=false;submit.disabled=false;if(A.mode==='register')submit.textContent='Sign up · it’s free';else if(A.mode==='login')submit.textContent='Log in';else if(A.mode==='forgot')submit.textContent='Send reset link';else if(A.mode==='reset')submit.textContent='Save new password'}});
G.authSignOut=async()=>{if(location.protocol!=='file:'){if(G.state)G.saveSilent?.();try{await api('/auth/logout',{method:'POST',body:'{}'})}catch{}}A.user=null;G.state=null;G.running=false;G.closePanel?.();document.getElementById('start-screen').classList.remove('hide','creator-active');document.getElementById('life-setup').hidden=true;root.hidden=false;mode('login')};document.getElementById('auth-signout').onclick=G.authSignOut;
document.getElementById('auth-tab-login').setAttribute('aria-selected','false');mode(new URLSearchParams(location.search).has('login')?'login':'register');
if(location.protocol==='file:'){A.user={id:'local-preview',username:'preview',displayName:'Local Preview',avatar:{}};root.hidden=true;window.addEventListener('load',()=>{setup();A.ready=true},{once:true})}else (async()=>{try{if(new URLSearchParams(location.search).has('reset'))return;const d=await api('/auth/me');A.user=d.user;setup()}catch(e){root.hidden=false;if(!base||/account API is not connected|not connected to GitHub Pages/i.test(e.message))setMessage('This public GitHub Pages site needs the HTTPS Node account server connected before real registration or login can work.','error')}finally{A.ready=true}})();
})();

