(function(){
const G=window.Game,root=document.getElementById('start-screen'),screen=document.getElementById('life-setup'),panel=document.getElementById('creator-content'),preview=document.getElementById('sim-preview');
if(!root||!screen||!panel)return;
const traits=[['💼','Hustler','Sees money everywhere. Hustle skill grows faster and bosses notice.'],['🍲','Foodie','Lives for jollof. Cooking is fun and food is extra enjoyable.'],['🎉','Owambe Spirit','Always ready to spray money. Parties and dancing hit different.'],['💪','Gym Rat','Leg day every day. Fitness grows fast and workouts feel good.'],['😉','Smooth Talker','Mouth sweet like honey. Charisma grows fast and socials land better.'],['😴','Lazy Bone','Why stand when you can sit? Energy lasts longer.'],['🧼','Clean Pikin','Always fresh. Hygiene drops slower than others.'],['🌙','Night Crawler','Abuja gets lively after dark. Loves a late night out.'],['💻','Tech Bro or Sis','Always has a new business idea. Coding and tech skills grow faster.'],['🎵','Musical','Hums Afrobeats in the shower. Music skill grows faster.']];
const dreams=[['👔','Oga at the Top','Reach the top level of any career.'],['🏡','Abuja Property Mogul','Build a net worth of ₦1,000,000.'],['🎤','Afrobeats Star','Max out the Music skill (level 10).'],['🤝',"Everybody’s Padi",'Become best friends with 4 people.'],['🦄','Jabi Startup Star','Build a successful startup in Abuja.']];
const origins=[['🏦','Hustler from Nyanya','You learned to stretch every naira and spot an opportunity.','Start with ₦60,000 · a loan to repay each week'],['🎓','UniAbuja Pikin','Student life in Gwagwalada: lectures, friends and big plans.','Start with ₦18,000 · student-friendly rent'],['🧺','Garki Market Family','You grew up around traders who know how to make a deal.','Start with ₦35,000 · stronger business instincts'],['🏡','Maitama Legacy','A soft landing, a good network and high expectations.','Start with ₦120,000 · higher neighbourhood costs']];
const homes=[['🎓','UniAbuja Student · Gwagwalada','Lectures, late study sessions and a bunk in a student hostel near campus.',14000,1200,'Student life','Gwagwalada'],['🛏️','Face-me-I-face-you · Nyanya','One room in a shared compound, busy neighbours and an affordable start.',76000,2400,'Hard start','Nyanya'],['🏠','Self-contain · Kubwa','Your own toilet and kitchen corner, with room to build your next move.',96000,6000,'Balanced','Kubwa']];
const palette={skin:['#c58c68','#ae7453','#925b3e','#75442f','#663a29','#512c21','#3d211b'],hair:['#171412','#2b1d18','#4a2c20','#74442e','#9a5c31','#d0aa75','#55218d'],clothes:['#287bdd','#20a978','#eb4d5a','#f09b36','#8a5bea','#e94b91','#19a99b','#202a3d','#f3eee4','#c7a22e']};
const colorNames={skin:['Honey','Golden brown','Chestnut','Deep brown','Espresso','Dark cocoa','Ebony'],hair:['Black','Soft black','Dark brown','Brown','Auburn','Honey blonde','Violet'],clothes:['Blue','Green','Coral','Orange','Purple','Pink','Teal','Midnight','Cream','Gold']};
const C=G.creator={step:0,choices:{gender:'woman',hair:'braids',outfit:'casual',fabric:'plain',skin:3,hairColor:0,top:1,bottom:7,traits:[],dream:0,origin:0,home:2},rotation:0,user:null};
const stepNames=['Look','Personality','Dream','Birth lottery','Home'];
function safe(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function syncFields(){const c=C.choices;document.getElementById('gender').value=c.gender;document.getElementById('hair').value=['braids','curls','fade'].includes(c.hair)?c.hair:'curls';document.getElementById('skin').value=c.skin<2?'light':c.skin<3?'medium':'dark';document.getElementById('outfit').value=({0:'blue',1:'green',2:'coral',3:'green',4:'blue',5:'coral',6:'green',7:'blue',8:'green',9:'coral'})[c.top];document.getElementById('creator-avatar-name').textContent='@'+(C.user?.username||'your_sim');preview.dataset.gender=c.gender;preview.dataset.hair=c.hair;preview.style.setProperty('--sim-skin',palette.skin[c.skin]);preview.style.setProperty('--sim-hair',palette.hair[c.hairColor]);preview.style.setProperty('--sim-shirt',palette.clothes[c.top]);preview.style.setProperty('--sim-bottoms',palette.clothes[c.bottom])}
function pills(group,values,selected,extra=''){return `<div class="creator-pills ${extra}">${values.map((v,i)=>`<button type="button" class="creator-pill ${i===selected?'active':''}" data-group="${group}" data-value="${i}" ${v.color?`aria-label="${safe(v.label)}" title="${safe(v.label)}" style="--chip:${v.color}"`:''}>${v.color?'<i></i>':safe(v)}</button>`).join('')}</div>`}
function look(){const c=C.choices;const hair=['Low cut','Bald','Curls','Afro','Locs','Braids','Classic','Ponytail','Bun','Gele'],hairIds=['lowcut','bald','curls','afro','locs','braids','classic','ponytail','bun','gele'];const outfits=['Casual','Hoodie','Office','Chill','Site work','Owambe'],outfitIds=['casual','hoodie','office','chill','sitework','owambe'];const fabrics=['Plain','Ankara','Adire','Aso-oke'],fabricIds=['plain','ankara','adire','aso-oke'];return `<p class="creator-prompt">Make your Sim feel like you.</p><label class="creator-label">Your Sim’s name<input id="creator-name" value="${safe(document.getElementById('name-input').value)}" maxlength="20" placeholder="Choose a name"></label><div class="creator-group"><b>Body</b><div class="creator-pills"><button type="button" class="creator-pill ${c.gender==='woman'?'':'active'}" data-group="gender" data-value="man">Man</button><button type="button" class="creator-pill ${c.gender==='woman'?'active':''}" data-group="gender" data-value="woman">Woman</button></div></div><div class="creator-group"><b>Hairstyle</b>${pills('hair',hair,hairIds.indexOf(c.hair))}</div><div class="creator-group"><b>Outfit</b>${pills('outfit',outfits,outfitIds.indexOf(c.outfit))}</div><div class="creator-group"><b>Fabric</b>${pills('fabric',fabrics,fabricIds.indexOf(c.fabric))}</div><div class="creator-group"><b>Skin tone</b>${pills('skin',palette.skin.map((color,i)=>({color,label:colorNames.skin[i]})),c.skin,'creator-swatches')}</div><div class="creator-group"><b>Hair colour</b>${pills('hairColor',palette.hair.map((color,i)=>({color,label:colorNames.hair[i]})),c.hairColor,'creator-swatches')}</div><div class="creator-group"><b>Outfit colour</b>${pills('top',palette.clothes.map((color,i)=>({color,label:colorNames.clothes[i]})),c.top,'creator-swatches')}</div><div class="creator-group"><b>Bottoms</b>${pills('bottom',palette.clothes.map((color,i)=>({color,label:colorNames.clothes[i]})),c.bottom,'creator-swatches')}</div>`}
function personality(){return `<p class="creator-prompt">Choose 2 traits for ${safe(C.user?.username||'your Sim')}.</p><div class="creator-cards creator-traits">${traits.map((t,i)=>`<button type="button" class="creator-choice ${C.choices.traits.includes(i)?'chosen':''}" data-group="traits" data-value="${i}"><span>${t[0]}</span><b>${t[1]}</b><small>${t[2]}</small></button>`).join('')}</div>`}
function dream(){return `<p class="creator-prompt">What’s ${safe(C.user?.username||'your Sim')}’s big dream?</p><div class="creator-options">${dreams.map((d,i)=>`<button type="button" class="creator-option ${C.choices.dream===i?'chosen':''}" data-group="dream" data-value="${i}"><span>${d[0]}</span><div><b>${d[1]}</b><small>${d[2]}</small></div></button>`).join('')}</div>`}
function origin(){const x=origins[C.choices.origin];return `<p class="creator-prompt">Every Abuja story starts somewhere. What was ${safe(C.user?.username||'your Sim')} born into?</p><article class="lottery-card"><div>${x[0]}</div><h2>${x[1]}</h2><p>${x[2]}</p><strong>${x[3]}</strong></article><div class="creator-dots">${origins.map((_,i)=>`<button type="button" aria-label="Birth story ${i+1}" class="${i===C.choices.origin?'active':''}" data-group="origin" data-value="${i}"></button>`).join('')}</div><button type="button" class="creator-reroll" data-group="origin" data-random="true">🎲 Draw another birth story</button>`}
function home(){return `<p class="creator-prompt">Where will ${safe(C.user?.username||'your Sim')} live? Rent is paid every Saturday.</p><div class="creator-options">${homes.map((h,i)=>`<button type="button" class="creator-home ${C.choices.home===i?'chosen':''}" data-group="home" data-value="${i}"><div class="creator-home-title"><b>${h[0]} ${h[1]}</b><span>${h[5]}</span></div><p>${h[2]}</p><div><strong>Start with ₦${h[3].toLocaleString()}</strong><b>Rent ₦${h[4].toLocaleString()}/wk</b></div></button>`).join('')}</div>`}
function render(){document.getElementById('creator-step-name').textContent=stepNames[C.step];document.getElementById('creator-progress').innerHTML=stepNames.map((_,i)=>`<i class="${i<=C.step?'done':''}"></i>`).join('');document.getElementById('creator-back').disabled=C.step===0;document.getElementById('creator-next').textContent=C.step===4?'Move in':'Next';document.getElementById('creator-continue').textContent=C.step===4?'Move in':C.step===1&&C.choices.traits.length!==2?`Choose ${2-C.choices.traits.length} more`:'Continue';document.getElementById('creator-continue').disabled=C.step===1&&C.choices.traits.length!==2;panel.innerHTML=[look,personality,dream,origin,home][C.step]();syncFields()}
function goNext(){if(C.step===1&&C.choices.traits.length!==2)return;if(C.step<4){C.step++;render();return}document.getElementById('new-game').click()}
C.restore=user=>{C.user=user;const a=user?.avatar||{},find=(list,value)=>{const i=list.findIndex(row=>row[1]===value);return i<0?null:i};if(Number.isInteger(a.skinTone))C.choices.skin=a.skinTone;if(Number.isInteger(a.hairColor))C.choices.hairColor=a.hairColor;if(Number.isInteger(a.topColor))C.choices.top=a.topColor;if(Number.isInteger(a.bottomColor))C.choices.bottom=a.bottomColor;if(a.gender)C.choices.gender=a.gender;if(a.hairStyle)C.choices.hair=a.hairStyle;if(a.clothingStyle)C.choices.outfit=a.clothingStyle;if(a.fabric)C.choices.fabric=a.fabric;const dream=find(dreams,a.dream),origin=find(origins,a.birthStory),home=homes.findIndex(row=>row[6]===a.home||row[1]===a.home);if(dream!==null&&dream!==undefined)C.choices.dream=dream;if(origin!==null&&origin!==undefined)C.choices.origin=origin;if(home>=0)C.choices.home=home;if(Array.isArray(a.traits))C.choices.traits=a.traits.map(t=>traits.findIndex(row=>row[1]===t)).filter(i=>i>=0).slice(0,2);syncFields()};C.open=(user,hasSave)=>{C.restore(user);root.classList.add('creator-active');screen.hidden=false;document.getElementById('continue-game').hidden=!hasSave;document.getElementById('creator-saved').hidden=!hasSave;render()};
C.apply=()=>{const c=C.choices,h=homes[c.home],origin=origins[c.origin];if(!G.state)return;G.state.gender=c.gender;G.state.skin=document.getElementById('skin').value;G.state.hair=c.hair;G.state.outfit=document.getElementById('outfit').value;G.state.home=h[1];G.state.rent=h[4];G.state.cash=Math.max(G.state.cash,h[3]-h[4]*2);G.state.traits=c.traits.map(i=>traits[i][1]);G.state.dream=dreams[c.dream][1];G.state.birthStory=origin[1];G.state.fabric=c.fabric;G.state.hairColor=colorNames.hair[c.hairColor];G.state.outfitColor=colorNames.clothes[c.top];G.state.bottomColor=colorNames.clothes[c.bottom];G.state.outfitStyle=c.outfit;G.state.birthBonus=[60000,18000,35000,120000][c.origin];};
C.avatar=()=>({gender:C.choices.gender,skin:document.getElementById('skin').value,hair:document.getElementById('hair').value,outfit:document.getElementById('outfit').value,fabric:C.choices.fabric,skinTone:C.choices.skin,hairColor:C.choices.hairColor,topColor:C.choices.top,bottomColor:C.choices.bottom,hairStyle:C.choices.hair,clothingStyle:C.choices.outfit,traits:C.choices.traits.map(i=>traits[i][1]),dream:dreams[C.choices.dream][1],birthStory:origins[C.choices.origin][1],home:homes[C.choices.home][6],onboardingComplete:true});
panel.addEventListener('click',e=>{const b=e.target.closest('[data-group]');if(!b)return;const group=b.dataset.group;if(b.dataset.random==='true'){C.choices.origin=Math.floor(Math.random()*origins.length)}else if(group==='traits'){const i=Number(b.dataset.value),arr=C.choices.traits;if(arr.includes(i))C.choices.traits=arr.filter(n=>n!==i);else if(arr.length<2)arr.push(i)}else if(['skin','hairColor','top','bottom'].includes(group))C.choices[group]=Number(b.dataset.value);else if(group==='gender')C.choices.gender=b.dataset.value;else if(group==='hair')C.choices.hair=['lowcut','bald','curls','afro','locs','braids','classic','ponytail','bun','gele'][Number(b.dataset.value)];else if(group==='outfit')C.choices.outfit=['casual','hoodie','office','chill','sitework','owambe'][Number(b.dataset.value)];else if(group==='fabric')C.choices.fabric=['plain','ankara','adire','aso-oke'][Number(b.dataset.value)];else C.choices[group]=Number(b.dataset.value);render()});
document.getElementById('creator-back').onclick=()=>{if(C.step>0){C.step--;render()}else{root.classList.remove('creator-active');screen.hidden=true;document.getElementById('account-auth').hidden=false}};
document.getElementById('creator-signout').onclick=()=>G.authSignOut?.();
document.getElementById('creator-saved').onclick=()=>document.getElementById('continue-game').click();
document.getElementById('creator-next').onclick=goNext;document.getElementById('creator-continue').onclick=goNext;
document.getElementById('creator-random').onclick=()=>{C.choices.skin=Math.floor(Math.random()*palette.skin.length);C.choices.hairColor=Math.floor(Math.random()*palette.hair.length);C.choices.top=Math.floor(Math.random()*palette.clothes.length);C.choices.bottom=Math.floor(Math.random()*palette.clothes.length);C.choices.gender=Math.random()<.5?'woman':'man';C.choices.hair=['braids','afro','curls','fade','locs'][Math.floor(Math.random()*5)];render()};
panel.addEventListener('input',e=>{if(e.target.id==='creator-name'){document.getElementById('name-input').value=e.target.value;document.getElementById('creator-avatar-name').textContent='@'+(C.user?.username||'your_sim')}});
let dragX=null;preview.addEventListener('pointerdown',e=>{dragX=e.clientX;preview.setPointerCapture?.(e.pointerId)});preview.addEventListener('pointermove',e=>{if(dragX===null)return;C.rotation=Math.max(-28,Math.min(28,C.rotation+(e.clientX-dragX)*.55));dragX=e.clientX;preview.style.transform=`perspective(900px) rotateY(${C.rotation}deg)`});preview.addEventListener('pointerup',()=>dragX=null);preview.addEventListener('pointercancel',()=>dragX=null);
})();

