(function(){const G=window.Game;let canvas=document.getElementById('world'),ctx=canvas.getContext('2d'),mini=document.getElementById('minimap'),mctx=mini.getContext('2d');let dpr=1,last=performance.now(),hudTimer=0,weatherTimer=0;function resize(){dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(innerWidth*dpr);canvas.height=Math.floor(innerHeight*dpr);G.view.w=innerWidth;G.view.h=innerHeight;G.view.scale=Math.max(.62,Math.min(1.12,innerWidth/1450));}window.addEventListener('resize',resize);resize();
function drawInterior(){let w=innerWidth,h=innerHeight;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#10182d';ctx.fillRect(0,0,w,h);let cx=w*.51,cy=h*.53,roomW=Math.min(w*.65,780),roomH=Math.min(h*.55,440);ctx.save();ctx.translate(cx,cy);ctx.fillStyle='#b9a88c';ctx.beginPath();ctx.moveTo(-roomW*.52,-roomH*.15);ctx.lineTo(0,-roomH*.5);ctx.lineTo(roomW*.52,-roomH*.15);ctx.lineTo(roomW*.52,roomH*.36);ctx.lineTo(0,roomH*.57);ctx.lineTo(-roomW*.52,roomH*.36);ctx.closePath();ctx.fill();ctx.fillStyle='#303035';ctx.beginPath();ctx.moveTo(-roomW*.52,-roomH*.15);ctx.lineTo(0,-roomH*.5);ctx.lineTo(0,roomH*.20);ctx.lineTo(-roomW*.52,roomH*.36);ctx.closePath();ctx.fill();ctx.fillStyle='#242832';ctx.beginPath();ctx.moveTo(0,-roomH*.5);ctx.lineTo(roomW*.52,-roomH*.15);ctx.lineTo(roomW*.52,roomH*.36);ctx.lineTo(0,roomH*.2);ctx.closePath();ctx.fill();ctx.fillStyle='#3e4042';ctx.beginPath();ctx.moveTo(-roomW*.52,roomH*.36);ctx.lineTo(0,roomH*.2);ctx.lineTo(roomW*.52,roomH*.36);ctx.lineTo(0,roomH*.57);ctx.closePath();ctx.fill();ctx.strokeStyle='#62666a';ctx.lineWidth=1;for(let i=1;i<8;i++){ctx.beginPath();ctx.moveTo(-roomW*.52+i*roomW/8,roomH*.36-i*roomH*.07);ctx.lineTo(0+i*roomW/16,roomH*.57-i*roomH*.045);ctx.stroke()}
// custom furniture shapes
ctx.fillStyle='#785138';ctx.fillRect(-roomW*.24,roomH*.03,roomW*.24,roomH*.10);ctx.fillStyle='#19906c';ctx.fillRect(-roomW*.22,roomH*.01,roomW*.20,roomH*.08);ctx.fillStyle='#78523a';ctx.fillRect(roomW*.12,-roomH*.22,roomW*.23,roomH*.13);ctx.fillStyle='#714da1';ctx.fillRect(roomW*.14,-roomH*.21,roomW*.19,roomH*.085);ctx.fillStyle='#f4eee0';ctx.fillRect(roomW*.28,-roomH*.205,roomW*.05,roomH*.045);ctx.fillStyle='#593b27';ctx.fillRect(-roomW*.47,-roomH*.11,roomW*.06,roomH*.21);ctx.fillStyle='#2b343b';ctx.fillRect(-roomW*.08,-roomH*.03,roomW*.17,roomH*.13);ctx.fillStyle='#dfc497';ctx.fillRect(roomW*.28,roomH*.07,roomW*.14,roomH*.10);ctx.fillStyle='#c7b18c';ctx.fillRect(roomW*.29,roomH*.06,roomW*.13,roomH*.07);ctx.fillStyle='#f4df9a';ctx.beginPath();ctx.arc(0,-roomH*.23,8,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 13px DM Sans';ctx.textAlign='center';ctx.fillText(G.world.buildings.find(b=>b.id===G.state.inside)?.name||'Interior',0,roomH*.72);ctx.restore();ctx.textAlign='left';}
function renderWorld(){if(!G.state)return;let w=G.view.w,h=G.view.h,scale=G.view.scale;if(G.state.inside){drawInterior();return}let camera={x:G.clamp(G.state.x-w/(2*scale),0,G.W-w/scale),y:G.clamp(G.state.y-h/(2*scale),0,G.H-h/scale)};G.view.cameraX=camera.x;G.view.cameraY=camera.y;ctx.setTransform(dpr,0,0,dpr,0,0);try{G.world.draw3D(ctx,scale,dpr,w,h)}catch(error){console.error('Isometric city rendering failed:',error);ctx.setTransform(dpr,0,0,dpr,0,0);G.world.draw(ctx,camera,scale);if(!G.ui.renderWarning){G.ui.renderWarning=true;G.toast('3D view failed to start; showing the city map view instead.')}}if(G.state.weather==='Rain'||G.state.weather==='Heavy rain'||G.state.weather==='Storm'){ctx.strokeStyle='#d9efff9a';ctx.lineWidth=1;for(let r of G.world.rain){r.x=(r.x+dtGlobal*.00009*r.speed)%1;r.y=(r.y+dtGlobal*.00035*r.speed)%1;ctx.beginPath();ctx.moveTo(r.x*w,r.y*h);ctx.lineTo(r.x*w-7,r.y*h+12);ctx.stroke()}}let fade=G.state.hour<6||G.state.hour>=19?Math.min(.48,G.state.hour<6?(6-G.state.hour)*.055:(G.state.hour-18)*.055):0;if(fade){ctx.fillStyle='rgba(9,20,45,'+fade+')';ctx.fillRect(0,0,w,h)}drawMinimap(camera,scale);}
function drawMinimap(camera,scale){let w=mini.width,h=mini.height;mctx.clearRect(0,0,w,h);mctx.fillStyle='#a7bf91';mctx.fillRect(0,0,w,h);mctx.fillStyle='#687373';for(let x of G.world.roadX)mctx.fillRect(x/G.W*w-3,0,6,h);for(let y of G.world.roadY)mctx.fillRect(0,y/G.H*h-3,w,6);mctx.fillStyle='#59abc8';mctx.fillRect(w*.82,0,w*.18,h);mctx.fillStyle='#f3ba60';for(let b of G.world.buildings)mctx.fillRect(b.x/G.W*w,b.y/G.H*h,2,2);mctx.fillStyle='#dd365d';mctx.beginPath();mctx.arc(G.state.x/G.W*w,G.state.y/G.H*h,4,0,7);mctx.fill();}
let dtGlobal=0;function frame(now){let dt=Math.min(.045,(now-last)/1000||0);last=now;dtGlobal=now;G.advance(dt);Player.update(dt);renderWorld();updateHud(dt);if(now-G.lastSave>45000&&G.state){G.saveSilent();G.lastSave=now}requestAnimationFrame(frame)}
function updateHud(dt){let s=G.state;if(!s)return;hudTimer-=dt;if(hudTimer>0)return;hudTimer=.22;document.getElementById('clock').textContent=G.clockText();let real=G.timeInfo();for(const [id,value] of [['phone-status-time',real.phoneTime],['phone-home-time',real.phoneTime],['phone-home-date',real.dateLine]]){let node=document.getElementById(id);if(node)node.textContent=value}document.getElementById('weather').textContent=G.weatherEmoji()+' '+s.weather;document.getElementById('mood').textContent=(s.happiness>70?'🙂 Feeling good':s.happiness>35?'😐 Getting by':'🙁 Feeling low');document.getElementById('money').innerHTML=G.money(s.cash)+' <span>＋</span>';document.getElementById('district').textContent=s.inside?G.world.buildings.find(b=>b.id===s.inside)?.name:'Wuse District';document.getElementById('portrait').textContent=s.gender==='man'?'👨🏾':'👩🏾';let arr=[['❤',s.health],['🍲',s.hunger],['⚡',s.energy],['☻',s.happiness],['💪',s.fitness],['✦',Math.min(100,s.reputation*3)]];document.getElementById('meters').innerHTML=arr.map(x=>`<span class="meter" title="${x[0]} ${Math.round(x[1])}%">${x[0]}<b class="meter-track"><i class="meter-fill" style="width:${G.clamp(x[1],0,100)}%;background:${x[1]<25?'#ec754d':''}"></i></b></span>`).join('');let m=G.missionsList[s.missions];document.getElementById('mission-title').textContent=m?m[0]:'A life of your own';document.getElementById('mission-text').textContent=m?m[1]:'The opening story is complete. Keep building your life.';document.getElementById('hint').textContent=G.ui.hint;document.getElementById('hint').style.display=G.ui.hint?'block':'none';document.getElementById('rain').style.opacity=['Rain','Heavy rain','Storm'].includes(s.weather)?(s.weather==='Storm'?.4:.24):0;let night=s.hour<6||s.hour>=19;document.getElementById('night').style.background=night?'rgba(15,26,54,.14)':'transparent';}
function start(name,gender,skin,hair,outfit){G.newState(name,gender,skin,hair,outfit);document.getElementById('start-screen').classList.add('hide');G.running=true;G.saveSilent();G.toast('Welcome to the city, '+G.state.name+'. Use WASD to explore.');}
document.getElementById('new-game').onclick=()=>start(document.getElementById('name-input').value.trim()||'Amara',document.getElementById('gender').value,document.getElementById('skin').value,document.getElementById('hair').value,document.getElementById('outfit').value);document.getElementById('continue-game').onclick=()=>{if(G.load()){document.getElementById('start-screen').classList.add('hide');G.running=true;G.toast('Welcome back, '+G.state.name+'.')}else G.toast('No saved life on this device yet.')};
if(!G.load())document.getElementById('continue-game').style.display='none';else document.getElementById('name-input').value=G.state.name;
document.querySelectorAll('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>{let p=b.dataset.panel;if(p==='home'){G.closePanel();G.state.inside=null;return}if(p==='map')G.openPanel('map');else if(p==='phone')G.openPanel('phone','apps');else if(p==='inventory')G.openPanel('inventory');else if(p==='save')G.openPanel('save');document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('selected',x===b))}));document.getElementById('close-panel').onclick=()=>G.closePanel();document.getElementById('shade').addEventListener('click',e=>{if(e.target.id==='shade')G.closePanel()});document.getElementById('mission-action').onclick=()=>G.openPanel('mission');document.getElementById('money').onclick=()=>G.openPanel('phone','bank');
canvas.addEventListener('click',e=>{if(!G.state||G.ui.panel)return;let rect=canvas.getBoundingClientRect(),scale=G.view.scale,ix=(e.clientX-rect.left-innerWidth/2)/scale,iy=(e.clientY-rect.top-innerHeight/2)/scale,x=G.state.x+(ix/.74+iy/.38)/2,y=G.state.y+(iy/.38-ix/.74)/2;let b=G.world.buildings.find(v=>x>v.x-15&&x<v.x+v.w+15&&y>v.y-40&&y<v.y+v.h+20);if(b){G.state.x=b.x+b.w/2;G.state.y=b.y+b.h+34;G.toast('You are at '+b.name+'. Press E to enter.')}});
// Touch controls for phones/tablets
if(matchMedia('(pointer:coarse)').matches){let pad=document.createElement('div');pad.className='touch-pad';pad.innerHTML='<button data-key="arrowup">▲</button><button data-key="arrowleft">◀</button><button data-key="arrowdown">▼</button><button data-key="arrowright">▶</button><div class="touch-actions"><button data-key="e">E</button><button data-key="f">F</button></div>';document.getElementById('game').appendChild(pad);pad.querySelectorAll('button').forEach(btn=>{let key=btn.dataset.key;btn.addEventListener('pointerdown',e=>{e.preventDefault();G.keys[key]=true});['pointerup','pointercancel','pointerleave'].forEach(ev=>btn.addEventListener(ev,()=>G.keys[key]=false))})}
G.saveSilent=function(){try{localStorage.setItem('naija-life-save',JSON.stringify({state:G.state,at:Date.now()}))}catch{}};
G.running=true;requestAnimationFrame(frame);
})();





