/* Secure purchase UI. Game money is credited by the server only after provider verification. */
(function(){
const G=window.Game;
G.paymentOnline=false;G.paymentState={user:null,wallet:null,packages:[],currencies:[],networks:{},transaction:null,error:'',busy:false,checked:false};let economyQueue=Promise.resolve(),settlePending='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(path,opts={})=>{const r=await fetch(path,{credentials:'same-origin',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'The account server is unavailable.');return d};
function fmt(n){return '₦'+Math.round(Number(n||0)).toLocaleString('en-NG')}
function show(){if(G.ui.panel==='phone'&&G.ui.panelTab==='bank')G.renderPanel('phone','bank')}
function syncWallet(wallet){const s=G.paymentState;s.wallet={...(s.wallet||{}),...wallet};if(G.state){G.state.cash=Number(wallet.cash||0);G.state.bank=Number(wallet.bank||0);if(Object.hasOwn(wallet,'job'))G.state.job=wallet.job;if(Object.hasOwn(wallet,'jobLevel'))G.state.jobLevel=Number(wallet.jobLevel);if(Object.hasOwn(wallet,'shifts'))G.state.shiftsCompleted=Number(wallet.shifts);if(Object.hasOwn(wallet,'rent'))G.state.rent=Number(wallet.rent);if(Object.hasOwn(wallet,'investments'))G.state.investments=Number(wallet.investments);if(Object.hasOwn(wallet,'business'))G.state.business=wallet.business?G.state.business||{name:'Corner Shop',stock:12,price:900,employees:0,profit:0}:null}}
function economy(operation,extra={}){const run=async()=>{const d=await api('/api/economy/action',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({operation,...extra})});syncWallet(d.wallet);return d.wallet};const task=economyQueue.then(run,run);economyQueue=task.catch(()=>{});return task}
G.paymentLoad=async function(){const s=G.paymentState;s.checked=true;try{const [me,wallet,packs,txs]=await Promise.all([api('/api/auth/me'),api('/api/wallet'),api('/api/payments/packages'),api('/api/payments')]);s.user=me.user;s.wallet=wallet;s.packages=packs.packages||[];s.currencies=packs.cryptoCurrencies||[];s.networks=packs.cryptoNetworks||{};if(txs.transactions?.length&&!s.transaction)s.transaction=txs.transactions.find(t=>!['Completed','Failed','Expired','Refunded'].includes(t.status))||null;s.error='';G.paymentOnline=true;syncWallet(wallet);G.saveSilent?.();economy('settle').then(w=>{syncWallet(w);G.saveSilent?.()}).catch(e=>console.warn('online settlement:',e.message))}catch(e){s.user=null;s.wallet=null;s.packages=[];s.error=e.message;G.paymentOnline=false}finally{s.checked=true}show()};
G.paymentAuth=async function(mode){const s=G.paymentState;s.busy=true;s.error='';show();try{const body={email:document.getElementById('pay-email')?.value,displayName:document.getElementById('pay-name')?.value,password:document.getElementById('pay-password')?.value};const d=await api('/api/auth/'+(mode==='register'?'register':'login'),{method:'POST',body:JSON.stringify(body)});s.user=d.user;await G.paymentLoad()}catch(e){s.error=e.message;show()}finally{s.busy=false}};
G.paymentLogout=async function(){try{await api('/api/auth/logout',{method:'POST',body:'{}'})}catch{}G.paymentOnline=false;G.paymentState={user:null,wallet:null,packages:[],currencies:[],networks:{},transaction:null,error:'',busy:false,checked:true};show()};
G.paymentCreate=async function(){const s=G.paymentState;s.busy=true;s.error='';show();try{const method=document.getElementById('pay-method')?.value,body={packageId:document.getElementById('pay-package')?.value,method,cryptoCurrency:document.getElementById('pay-crypto')?.value,network:document.getElementById('pay-network')?.value};const d=await api('/api/payments',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(body)});s.transaction=d.transaction;show();if(!['Completed','Failed','Expired','Refunded'].includes(s.transaction.status))G.paymentPoll()}catch(e){s.error=e.message;show()}finally{s.busy=false}};
G.paymentCheck=async function(id){const s=G.paymentState;s.busy=true;try{const d=await api('/api/payments/'+encodeURIComponent(id));s.transaction=d.transaction;const w=await api('/api/wallet');s.wallet=w;s.error=''}catch(e){s.error=e.message}finally{s.busy=false;show()}};
G.paymentPoll=function(){clearInterval(G.paymentPollTimer);G.paymentPollTimer=setInterval(async()=>{const t=G.paymentState.transaction;if(!t||['Completed','Failed','Expired','Refunded'].includes(t.status)){clearInterval(G.paymentPollTimer);return}await G.paymentCheck(t.id)},8000)};
G.paymentSelectMethod=function(){const cryptoBox=document.getElementById('crypto-fields');if(cryptoBox)cryptoBox.hidden=document.getElementById('pay-method')?.value!=='crypto'};
G.paymentRender=function(){const s=G.paymentState;let account;
 if(!s.user){account=`<div class="verified-auth"><b>Secure account required</b><p>Your payment history and verified wallet belong to your player account.</p><label>Email<input id="pay-email" type="email" autocomplete="email" placeholder="you@example.com"></label><label>Display name<input id="pay-name" maxlength="32" autocomplete="nickname" placeholder="Your player name"></label><label>Password<input id="pay-password" type="password" minlength="12" autocomplete="new-password" placeholder="At least 12 characters"></label><div class="pay-buttons"><button onclick="Game.paymentAuth('login')" ${s.busy?'disabled':''}>Sign in</button><button class="light" onclick="Game.paymentAuth('register')" ${s.busy?'disabled':''}>Create account</button></div>${s.error?`<p class="pay-error">${esc(s.error)}</p>`:''}</div>`;
 }else{
  const wallet=Number(s.wallet?.balance||0),t=s.transaction,packages=s.packages;
  const selectedCur=s.currencies[0]||'USDT',networkOptions=(s.networks[selectedCur]?[s.networks[selectedCur]]:[]).map(n=>`<option>${esc(n)}</option>`).join('');
  account=`<div class="protected-wallet"><small>SERVER-VERIFIED ACCOUNT WALLET</small><b>${fmt(wallet)}</b><span>Online account · ${esc(s.user.displayName)}</span><button class="wallet-logout" onclick="Game.paymentLogout()">Sign out</button></div>
  ${packages.length?`<div class="verified-auth"><b>Buy game money</b><p>Only server verification can complete a purchase and credit your playable balance.</p><label>Package<select id="pay-package">${packages.map(p=>`<option value="${esc(p.id)}">${esc(p.id)} · ${fmt(p.amountMinor/100)} → ${fmt(p.creditUnits)}</option>`).join('')}</select></label><label>Payment method<select id="pay-method" onchange="Game.paymentSelectMethod()"><option value="bank_transfer">Bank transfer</option><option value="crypto">Cryptocurrency</option></select></label><div id="crypto-fields" hidden><label>Crypto<select id="pay-crypto" onchange="Game.paymentCryptoChanged()">${s.currencies.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}</select></label><label>Network<select id="pay-network">${networkOptions}</select></label></div><button class="phone-wide" onclick="Game.paymentCreate()" ${s.busy?'disabled':''}>${s.busy?'Starting secure payment…':'Continue to payment instructions'}</button>${s.error?`<p class="pay-error">${esc(s.error)}</p>`:''}</div>`:`<div class="verified-auth"><b>Purchases are not configured yet</b><p>The server owner must set package prices and provider credentials in the server environment. No client-selected amount can be credited.</p>${s.error?`<p class="pay-error">${esc(s.error)}</p>`:''}</div>`}
  ${t?paymentCard(t):''}<button class="phone-wide light" onclick="Game.paymentLoad()">Refresh account</button>`;
 }
 return `<h4>REAL MONEY · VERIFIED PURCHASES</h4><p class="house-intro">In account mode, cash and bank balances are stored and changed by the game server.</p>${account}<div class="secure-note">Character progress remains saved on this device. This development build has real purchases disabled until package prices, provider credentials, and a hosted HTTPS backend are configured.</div>`;
};
function paymentCard(t){const i=t.instructions||{};let instructions='';if(t.method==='bank_transfer'&&i.accountNumber)instructions=`<div class="pay-instructions"><b>${esc(i.bank)} transfer</b><p>Account name: ${esc(i.accountName)}</p><p>Account number: <strong>${esc(i.accountNumber)}</strong></p><p>Amount: <strong>${fmt(t.amountMinor/100)}</strong></p><p>Reference: ${esc(i.reference)}</p><small>Transfer the exact amount before expiry. Verification is automatic.</small></div>`;else if(t.method==='crypto'&&i.address)instructions=`<div class="pay-instructions"><b>${esc(i.amount)} ${esc(i.currency)} · ${esc(i.network)}</b><p>Address:</p><code>${esc(i.address)}</code>${i.memo?`<p>Memo / tag: <strong>${esc(i.memo)}</strong></p>`:''}<p>Reference: ${esc(t.id)}</p><small>Use the exact network and amount. Wait for server confirmation.</small></div>`;
 return `<div class="verified-auth payment-status"><b>Transaction · ${esc(t.status)}</b><p>${fmt(t.amountMinor/100)} → ${fmt(t.creditUnits)} game money</p><small>Reference ${esc(t.id)} · ${esc(t.createdAt||'')}</small>${instructions}${!['Completed','Failed','Expired','Refunded'].includes(t.status)?`<button class="phone-wide light" onclick="Game.paymentCheck('${esc(t.id)}')">Check verified status</button>`:''}</div>`}
G.paymentCryptoChanged=function(){const c=document.getElementById('pay-crypto')?.value||'';const n=document.getElementById('pay-network');if(n)n.innerHTML=(G.paymentState.networks[c]?[G.paymentState.networks[c]]:[]).map(x=>`<option>${esc(x)}</option>`).join('')};
function actionCommand(kind,arg){if(kind==='deposit'||kind==='withdraw')return{operation:kind,amount:Number(document.getElementById('bank-amount')?.value)};if(kind==='movehome'){const h=String(arg||'').split('|');return{operation:kind,home:h[0]+'|'+h[1]}}if(kind==='event')return{operation:kind,choice:String(arg)};if(kind==='outfit')return{operation:kind,outfit:String(arg)};if(kind==='applyjob')return{operation:kind,job:String(arg||'')};if(kind==='quitjob')return{operation:kind};if(kind==='work'){if(G.state.energy<18)return null;return{operation:kind,job:G.state.job||''}}if(kind==='police')return G.state.wanted?{operation:'fine',wanted:G.state.wanted,reason:'pay'}:null;if(['transfer','business','businessupgrade','hire','buybike','buycar','fuel','repair','heal','water','upgradehome','gym','study','bus','club','delivery','movie','invest','bill','ad','date'].includes(kind))return{operation:kind};return undefined}
const baseAction=G.action;G.action=async function(kind,arg){if(!G.paymentOnline)return baseAction(kind,arg);const command=actionCommand(kind,arg);if(command===undefined)return baseAction(kind,arg);if(command===null)return baseAction(kind,arg);try{const before={cash:G.paymentState.wallet?.cash||0,bank:G.paymentState.wallet?.bank||0};const wallet=await economy(command.operation,command);syncWallet(before);if(kind==='repair')G.state.carDamage=Math.min(G.state.carDamage,5);baseAction(kind,arg);syncWallet(wallet);G.saveSilent?.()}catch(e){G.toast(e.message||'The server could not apply that game transaction.')}};
const baseEat=G.eat;G.eat=function(){if(!G.paymentOnline)return baseEat();const before={cash:G.paymentState.wallet?.cash||0,bank:G.paymentState.wallet?.bank||0};economy('eat').then(w=>{syncWallet(before);baseEat();syncWallet(w);G.saveSilent?.()}).catch(e=>G.toast(e.message))};
const baseMission=G.missionEvent;G.missionEvent=function(type,amount){if(!G.paymentOnline)return baseMission(type,amount);const before=G.state?.missions||0;baseMission(type,amount);if(G.state&&G.state.missions>before)economy('mission',{index:before}).then(w=>{syncWallet(w);G.saveSilent?.()}).catch(e=>G.toast('Mission reward could not be verified by the server.'))};
let arrestPending=false;const baseArrest=G.arrest;G.arrest=function(){if(!G.paymentOnline)return baseArrest();if(arrestPending)return;arrestPending=true;const wanted=G.state.wanted;economy('fine',{wanted}).then(w=>{syncWallet(w);baseArrest();syncWallet(w);G.saveSilent?.()}).catch(e=>{G.toast(e.message);setTimeout(()=>{arrestPending=false},2500)}).finally(()=>{if(!G.state.wanted)arrestPending=false})};
const baseNewState=G.newState;G.newState=function(...args){const result=baseNewState(...args);if(G.paymentOnline&&G.paymentState.wallet)syncWallet(G.paymentState.wallet);return result};const baseLoad=G.load;G.load=function(...args){const loaded=baseLoad(...args);if(loaded&&G.paymentOnline&&G.paymentState.wallet)syncWallet(G.paymentState.wallet);return loaded};
const baseAdvance=G.advance;G.advance=function(dt){if(!G.paymentOnline)return baseAdvance(dt);const today=G.timeInfo().dateKey;if(G.state.realDate!==today&&settlePending!==today){settlePending=today;economy('settle').then(w=>{syncWallet(w);G.saveSilent?.()}).catch(e=>{settlePending='';console.warn('online settlement:',e.message)})}baseAdvance(dt);if(G.paymentState.wallet)syncWallet(G.paymentState.wallet)};
if(window.Player){const baseCrime=Player.crime;Player.crime=function(){if(!G.paymentOnline)return baseCrime();const s=G.state,n=G.world.npcs.find(n=>Math.hypot(n.x-s.x,n.y-s.y)<50);if(!n||s.crimeCooldown>0)return baseCrime();economy('crime').then(w=>{syncWallet(w);baseCrime();syncWallet(w);G.saveSilent?.()}).catch(e=>G.toast(e.message))}}
const simulatorBank=window.phoneBank;window.phoneBank=function(){if(!G.paymentState.checked)queueMicrotask(()=>G.paymentLoad());const local=simulatorBank?simulatorBank().replace(/<button class="phone-wide" onclick="Game\.toast\('Your in-game wallet is ready\.'\)">[^<]*Top up wallet<\/button>/,''):'';return `${local}<section class="secure-wallet-section">${G.paymentRender()}</section>`};
G.paymentLoad();
})();
