(function(){const G=window.Game;
G.missionsList=[
['New in town','Walk 120 metres and get your bearings.','move',120,800],['A friendly face','Say hello to someone around the neighborhood.','talk',1,1100],['First paycheck','Complete a shift at a local business.','work',1,2200],['A proper plate','Buy and eat something fresh.','eat',1,1200],['Take the wheel','Drive around town for 300 metres.','drive',300,2600],['Running low','Visit a fuel station and refill your tank.','fuel',1,1400],['Known around town','Help people and build 5 reputation.','rep',5,3000],['A new connection','Build a friendship with a neighbor.','friend',1,1800],['Invest in yourself','Train at the gym or study at the university.','learn',1,2500],['Find your footing','Move into a better home or start a business.','upgrade',1,6000]
];
G.missionEvent=function(type,amount){let s=G.state;if(!s)return;let m=G.missionsList[s.missions];if(!m)return;if(m[2]==='rep'){s.goalProgress=Math.max(s.goalProgress||0,s.reputation)}else{if(m[2]!==type)return;s.goalProgress=(s.goalProgress||0)+(amount||1)};if(s.goalProgress>=m[3]){s.completed.push(m[0]);s.cash+=m[4];s.reputation+=1;s.missions++;s.goalProgress=0;G.toast('Mission complete: '+m[0]+' · '+G.money(m[4]));G.saveSilent()}};
G.arrest=function(){let s=G.state;let fine=Math.min(s.cash,Math.max(500,s.wanted*1200));s.cash-=fine;s.wanted=0;s.health=Math.max(25,s.health-10);s.inside=null;s.vehicle=null;s.x=1650;s.y=440;G.world.npcs=G.world.npcs.filter(n=>n.id!=='cop');G.missionEvent('police');G.toast('Police stopped you. Fine paid: '+G.money(fine)+'.');G.saveSilent()};
G.advance=function(dt){let s=G.state;if(!s)return;const tm=G.timeInfo();s.hour=tm.hour24;s.minute=Number(tm.minute);if(!s.realDate)s.realDate=tm.dateKey;else if(s.realDate!==tm.dateKey){s.realDate=tm.dateKey;s.day++;if(s.day%7===0){if(s.cash>=s.rent){s.cash-=s.rent;G.toast('Weekly rent paid: '+G.money(s.rent))}else s.happiness=Math.max(0,s.happiness-8)}if(s.business){let sales=Math.min(s.business.stock*s.business.price,Math.floor(s.business.stock*s.business.price*.16));let wages=s.business.employees*500;let income=Math.max(0,sales-wages);s.business.stock=Math.max(0,s.business.stock-Math.ceil(sales/Math.max(1,s.business.price)));s.business.profit+=income;s.bank+=income;if(income)G.toast('Your '+s.business.name+' earned '+G.money(income)+'.')}if(s.investments){let yieldAmount=Math.floor(s.investments*.05);s.bank+=yieldAmount;s.investmentReturns=(s.investmentReturns||0)+yieldAmount}}const hours=dt/3600;s.hunger=Math.max(0,s.hunger-.55*hours);s.energy=Math.max(0,s.energy-.12*hours);if(s.hunger<20)s.health=Math.max(0,s.health-.5*hours);if(s.health<30)s.happiness=Math.max(0,s.happiness-.4*hours);if(!G.weatherTimer)G.weatherTimer=75;G.weatherTimer-=dt;if(G.weatherTimer<=0){G.weatherTimer=75+Math.random()*60;s.weather=['Sunny','Cloudy','Rain','Heavy rain','Storm'][Math.floor(Math.random()*5)]}if(s.crimeCooldown>0)s.crimeCooldown=Math.max(0,s.crimeCooldown-dt);if(s.hour>21||s.hour<5)s.happiness=Math.max(0,s.happiness-dt*.00004)};G.weatherEmoji=function(){return ({Sunny:'☀',Cloudy:'☁',Rain:'🌧','Heavy rain':'🌧',Storm:'⛈'})[G.state.weather]||'☀'};
G.eat=function(){let s=G.state;if(s.cash<900){G.toast('You need ₦900 for a meal.');return}if(s.inventory.includes('Jollof meal')){G.toast('You already have a meal in your bag. Eat it from Inventory.');return}s.cash-=900;s.inventory.push('Jollof meal');G.toast('Bought a takeaway jollof meal.');G.renderPanel('building',G.ui.panelTab)};
G.consume=function(item){let s=G.state,i=s.inventory.indexOf(item);if(i<0)return;s.inventory.splice(i,1);if(item==='Jollof meal'){s.hunger=Math.min(100,s.hunger+38);s.happiness=Math.min(100,s.happiness+5);G.missionEvent('eat');G.toast('That hit the spot. Hunger restored.')}else if(item==='Water'){s.hunger=Math.min(100,s.hunger+6);s.energy=Math.min(100,s.energy+4);G.toast('You drank some water.')}else G.toast('Used '+item+'.');G.saveSilent();G.renderPanel('inventory')};
G.saveSilent=function(){try{localStorage.setItem('naija-life-save',JSON.stringify({state:G.state,at:Date.now()}))}catch{}};
})();






