0,l*.91,h*.62,w,paint);box(g,-l*.055,.12+h*.49,0,l*.46,h*.43,w*.86,mat('#8ec2ce',.23,.08));box(g,l*.37,.18,0,l*.16,.2,w*.92,mat('#faf0d3',.35,.25));for(const xx of [-l*.32,l*.32])for(const zz of [-w*.55,w*.55]){const wheel=new THREE.Mesh(wheelGeometry,mats.dark);wheel.rotation.z=Math.PI/2;wheel.position.set(xx,.35,zz);g.add(wheel)}parent.add(g);return g}
 function treeBatch(group,cx,cz,seed,count=42){
  const rand=seeded(seed),trunkGeo=new THREE.CylinderGeometry(.48,.78,7,7),crownGeo=new THREE.SphereGeometry(1,8,6),palmGeo=new THREE.BufferGeometry();
  palmGeo.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,.2,.3,0,.45,.32,0,.78,.15,0,1,0,0,.78,-.15,0,.45,-.32,0,.2,-.3,0],3));palmGeo.setIndex([0,1,7,1,2,7,2,6,7,2,3,6,3,5,6,3,4,5]);palmGeo.computeVertexNormals();sharedGeometry.add(trunkGeo,crownGeo);
  const trees=[],roadTrees=[],used=new Set(),collides=(x,z,r=8)=>G.world.buildings.some(b=>x>b.x-r&&x<b.x+b.w+r&&z>b.y-r&&z<b.y+b.h+r)||G.world.houseLots?.some(h=>x>h.x-r&&x<h.x+h.w+r&&z>h.y-r&&z<h.y+h.h+r)||G.world.cityLots?.some(b=>x>b.x-r&&x<b.x+b.w+r&&z>b.y-r&&z<b.y+b.h+r);
  const add=(x,z,palm=false)=>{if(x<cx+18||x>cx+chunkSize-18||z<cz+18||z>cz+chunkSize-18)return;if(used.has(`${Math.round(x/8)}:${Math.round(z/8)}`)||collides(x,z))return;used.add(`${Math.round(x/8)}:${Math.round(z/8)}`);trees.push({x,z,palm,scale:.78+rand()*.6,tone:rand()})};
  // Plant deliberate avenues on the verges, then fill open courtyards and green space.
  for(let i=0;i<G.world.roadX.length;i++){const x=G.world.roadX[i],width=roadWidth('x',i);if(x<cx-24||x>cx+chunkSize+24)continue;for(let z=cz+54;z<cz+chunkSize-30;z+=92){const side=(Math.floor(z/92)%2?1:-1);add(x+side*(width/2+9),z,true);if(width<20)add(x-side*(width/2+9),z+38,false)}}
  for(let i=0;i<G.world.roadY.length;i++){const z=G.world.roadY[i],width=roadWidth('y',i);if(z<cz-24||z>cz+chunkSize+24)continue;for(let x=cx+54;x<cx+chunkSize-30;x+=92){const side=(Math.floor(x/92)%2?1:-1);add(x,z+side*(width/2+9),true);if(width<20)add(x+38,z-side*(width/2+9),false)}}
  let tries=0;while(trees.length<count&&tries<count*12){tries++;add(cx+24+rand()*(chunkSize-48),cz+24+rand()*(chunkSize-48),rand()<.2)}
  if(!trees.length)return;
  const broad=trees.filter(t=>!t.palm),palms=trees.filter(t=>t.palm),trunks=new THREE.InstancedMesh(trunkGeo,mats.trunk,trees.length),crownTop=new THREE.InstancedMesh(crownGeo,mats.leaf,trees.length),crownLow=new THREE.InstancedMesh(crownGeo,mats.leaf2,trees.length),palmLeaves=new THREE.InstancedMesh(palmGeo,mats.leaf2,Math.max(1,palms.length*6)),dummy=new THREE.Object3D();let pi=0;
  trees.forEach((t,i)=>{const y=terrainY(t.x,t.z),s=t.scale;dummy.rotation.set(0,0,0);dummy.position.set(t.x,y+3.5*s,t.z);dummy.scale.set(s,s,s);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);trunks.setColorAt(i,color(t.tone>.65?'#7f5537':'#674b37'));
   if(t.palm){dummy.position.set(t.x,y+10*s,t.z);dummy.scale.set(1.5*s,1.8*s,1.5*s);dummy.updateMatrix();crownTop.setMatrixAt(i,dummy.matrix);crownTop.setColorAt(i,color('#2e7650'));for(let k=0;k<6;k++){dummy.position.set(t.x,y+11*s,t.z);dummy.rotation.set((rand()-.5)*.25,k*Math.PI/3,(-.2-rand()*.25));dummy.scale.set(9*s,2.1*s,.5*s);dummy.updateMatrix();palmLeaves.setMatrixAt(pi++,dummy.matrix)}}
   else{dummy.position.set(t.x,y+10*s,t.z);dummy.scale.set(6.1*s,6.8*s,6.1*s);dummy.updateMatrix();crownTop.setMatrixAt(i,dummy.matrix);crownTop.setColorAt(i,color(t.tone>.72?'#34764c':t.tone>.38?'#2f8051':'#397f4e'));dummy.position.set(t.x+1.1*s,y+7.5*s,t.z-.4*s);dummy.scale.set(6.5*s,4.1*s,6.2*s);dummy.updateMatrix();crownLow.setMatrixAt(i,dummy.matrix);crownLow.setColorAt(i,color('#32734a'))}
  });trunks.count=trees.length;crownTop.count=trees.length;crownLow.count=broad.length;palmLeaves.count=pi;trunks.castShadow=false;crownTop.castShadow=false;crownLow.castShadow=false;palmLeaves.castShadow=false;group.userData.treeCount=(group.userData.treeCount||0)+trees.length;group.add(trunks,crownTop,crownLow,palmLeaves);
 }
 function terrainStrip(parent,axis,pos,start,end,width,material,lift=.05){const steps=Math.max(1,Math.ceil((end-start)/72)),vertices=[],uvs=[],indices=[];for(let i=0;i<=steps;i++){const t=i/steps,v=start+(end-start)*t;for(const side of [-1,1]){const half=width/2*side,x=axis==='x'?pos+half:v,z=axis==='x'?v:pos+half;vertices.push(x,terrainY(x,z)+lift,z);uvs.push(x/8,z/8)}}for(let i=0;i<steps;i++){const a=i*2,b=a+1,c=a+2,d=a+3;if(axis==='x')indices.push(a,c,b,b,c,d);else indices.push(a,b,c,b,d,c)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));geo.setIndex(indices);geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,material);mesh.receiveShadow=true;parent.add(mesh);return mesh}
 function pathSurface(parent,a,b,width,material,lift=.12){const dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz),steps=Math.max(1,Math.ceil(len/64)),nx=dz/len,nz=-dx/len,vertices=[],uvs=[],indices=[];for(let i=0;i<=steps;i++){const t=i/steps,x=a[0]+dx*t,z=a[1]+dz*t;for(const side of [-1,1]){const px=x+nx*width*.5*side,pz=z+nz*width*.5*side;vertices.push(px,terrainY(px,pz)+lift,pz);uvs.push(px/8,pz/8)}}for(let i=0;i<steps;i++){const k=i*2;indices.push(k,k+2,k+1,k+1,k+2,k+3)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));geo.setIndex(indices);geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,material);mesh.receiveShadow=true;parent.add(mesh);return mesh}
 function roadWidth(axis,index){return axis==='x'?(index%5===0?30:index%2===0?20:13):(index%4===0?30:index%2===0?20:13)}
 function addRoadMedians(g,cx,cz){
  const segments=[],add=(axis,pos,start,end,otherRoads)=>{for(let along=start+54;along<end-30;along+=104){const cross=otherRoads.findIndex((p,i)=>Math.abs(along-p)<roadWidth(axis==='x'?'y':'x',i)/2+30);if(cross>=0)continue;segments.push({axis,pos,along})}};
  for(let i=0;i<G.world.roadX.length;i++){const x=G.world.roadX[i];if(roadWidth('x',i)>=28&&x>=cx-15&&x<=cx+chunkSize+15)add('x',x,cz,cz+chunkSize,G.world.roadY)}
  for(let i=0;i<G.world.roadY.length;i++){const y=G.world.roadY[i];if(roadWidth('y',i)>=28&&y>=cz-15&&y<=cz+chunkSize+15)add('y',y,cx,cx+chunkSize,G.world.roadX)}
  if(!segments.length)return;const grass=new THREE.InstancedMesh(boxGeometry(60,.18,2.25),mats.park,segments.length),curbs=new THREE.InstancedMesh(boxGeometry(60,.32,.3),mats.roadEdge,segments.length*2),dummy=new THREE.Object3D();let curbIndex=0;
  for(const s of segments){const x=s.axis==='x'?s.pos:s.along,z=s.axis==='x'?s.along:s.pos,y=terrainY(x,z)+.27;dummy.position.set(x,y,z);dummy.rotation.set(0,s.axis==='x'?Math.PI/2:0,0);dummy.scale.set(1,1,1);dummy.updateMatrix();grass.setMatrixAt(grass.count++,dummy.matrix);for(const side of [-1,1]){dummy.position.set(x+(s.axis==='x'?side*1.28:0),y+.06,z+(s.axis==='y'?side*1.28:0));dummy.updateMatrix();curbs.setMatrixAt(curbIndex++,dummy.matrix)}}
  g.add(grass,curbs);
 }
 function drawRoads(g,cx,cz){const minX=cx,maxX=cx+chunkSize,minZ=cz,maxZ=cz+chunkSize,marks=Math.ceil(chunkSize/30),dummy=new THREE.Object3D(),poles=[],heads=[];
  const addLine=(mesh,axis,pos,along)=>{const x=axis==='x'?pos:along,z=axis==='x'?along:pos;dummy.position.set(x,terrainY(x,z)+.25,z);dummy.updateMatrix();mesh.setMatrixAt(mesh.count++,dummy.matrix)};
  for(let i=0;i<(G.world.roadX||[]).length;i++){const x=G.world.roadX[i],width=roadWidth('x',i);if(x<minX-22||x>maxX+22)continue;terrainStrip(g,'x',x,cz,cz+chunkSize,width+5,mat('#bbb49f'),.04);terrainStrip(g,'x',x,cz,cz+chunkSize,width,mat('#3c4852',.94),.12);for(const side of [-1,1]){terrainStrip(g,'x',x+side*(width/2+1.1),cz,cz+chunkSize,.38,mat('#a7a092'),.16);terrainStrip(g,'x',x+side*(width/2+3.05),cz,cz+chunkSize,3.1,mat('#c8c2b2',.95),.18)}
   const center=new THREE.InstancedMesh(boxGeometry(.3,.12,11),mats.line,marks),lane=width>=20?new THREE.InstancedMesh(boxGeometry(.16,.08,7),mat('#e5e3d8'),marks*2):null;center.count=0;if(lane)lane.count=0;for(let z=cz+15;z<maxZ;z+=30){addLine(center,'x',x,z);if(lane){addLine(lane,'x',x-width*.23,z+4);addLine(lane,'x',x+width*.23,z+4)}}g.add(center);if(lane)g.add(lane);
   for(let z=cz+112;z<maxZ;z+=224){const side=(Math.floor(z/224)%2?1:-1),lampX=x+side*(width/2+4.5);dummy.position.set(lampX,terrainY(lampX,z)+3,z);dummy.updateMatrix();poles.push(dummy.matrix.clone());dummy.position.set(lampX-side*1.45,terrainY(lampX,z)+6,z);dummy.updateMatrix();heads.push(dummy.matrix.clone())}}
  for(let i=0;i<(G.world.roadY||[]).length;i++){const z=G.world.roadY[i],width=roadWidth('y',i);if(z<minZ-22||z>maxZ+22)continue;terrainStrip(g,'y',z,cx,cx+chunkSize,width+5,mat('#bbb49f'),.04);terrainStrip(g,'y',z,cx,cx+chunkSize,width,mat('#3c4852',.94),.12);for(const side of [-1,1]){terrainStrip(g,'y',z+side*(width/2+1.1),cx,cx+chunkSize,.38,mat('#a7a092'),.16);terrainStrip(g,'y',z+side*(width/2+3.05),cx,cx+chunkSize,3.1,mat('#c8c2b2',.95),.18)}
   const center=new THREE.InstancedMesh(boxGeometry(11,.12,.3),mats.line,marks),lane=width>=20?new THREE.InstancedMesh(boxGeometry(7,.08,.16),mat('#e5e3d8'),marks*2):null;center.count=0;if(lane)lane.count=0;for(let x=cx+15;x<maxX;x+=30){addLine(center,'y',z,x);if(lane){addLine(lane,'y',z+width*.23,x+4);addLine(lane,'y',z-width*.23,x+4)}}g.add(center);if(lane)g.add(lane);
   for(let x=cx+112;x<maxX;x+=224){const side=(Math.floor(x/224)%2?1:-1),lampZ=z+side*(width/2+4.5);dummy.position.set(x,terrainY(x,lampZ)+3,lampZ);dummy.updateMatrix();poles.push(dummy.matrix.clone());dummy.position.set(x,terrainY(x,lampZ)+6,lampZ-side*1.45);dummy.updateMatrix();heads.push(dummy.matrix.clone())}}
  const zebraX=new Map(),zebraY=new Map();for(let i=0;i<(G.world.roadX||[]).length;i++){const x=G.world.roadX[i],wx=roadWidth('x',i);if(x<minX||x>maxX)continue;for(let j=0;j<(G.world.roadY||[]).length;j++){const z=G.world.roadY[j],wz=roadWidth('y',j);if(z<minZ||z>maxZ)continue;const add=(map,key,px,pz)=>{if(!map.has(key))map.set(key,[]);dummy.position.set(px,terrainY(px,pz)+.21,pz);dummy.updateMatrix();map.get(key).push(dummy.matrix.clone())};for(const sign of [-1,1])for(let k=0;k<5;k++){add(zebraX,wx,x,z+sign*(wz/2+1.1+k*1.25));add(zebraY,wz,x+sign*(wx/2+1.1+k*1.25),z)}}}
  for(const[width,matrices]of zebraX){const mesh=new THREE.InstancedMesh(boxGeometry(Math.max(3,width-1),.08,.48),mat('#e5e3d8'),matrices.length);matrices.forEach((m,i)=>mesh.setMatrixAt(i,m));g.add(mesh)}for(const[width,matrices]of zebraY){const mesh=new THREE.InstancedMesh(boxGeometry(.48,.08,Math.max(3,width-1)),mat('#e5e3d8'),matrices.length);matrices.forEach((m,i)=>mesh.setMatrixAt(i,m));g.add(mesh)}
  if(poles.length){const poleMat=mat('#4e5655',.7,.35),lampMat=mat('#ffe0a4',.34,.15);lampMat.emissive=new THREE.Color('#8b6025');lampMat.emissiveIntensity=.42;const pm=new THREE.InstancedMesh(boxGeometry(.18,6,.18),poleMat,poles.length),hm=new THREE.InstancedMesh(boxGeometry(1.4,.22,.55),lampMat,heads.length);poles.forEach((m,i)=>pm.setMatrixAt(i,m));heads.forEach((m,i)=>hm.setMatrixAt(i,m));g.add(pm,hm)}
  const pathDashes=[];for(const path of G.world.roadPaths||[]){for(let i=1;i<path.points.length;i++){const a=path.points[i-1],b=path.points[i],len=Math.hypot(b[0]-a[0],b[1]-a[1]),steps=Math.max(1,Math.ceil(len/220)),nx=(b[1]-a[1])/len,nz=-(b[0]-a[0])/len;for(let j=0;j<steps;j++){const t0=j/steps,t1=(j+1)/steps,mid=(t0+t1)/2,mx=a[0]+(b[0]-a[0])*mid,mz=a[1]+(b[1]-a[1])*mid;if(mx<minX-25||mx>maxX+25||mz<minZ-25||mz>maxZ+25)continue;const p0=[a[0]+(b[0]-a[0])*t0,a[1]+(b[1]-a[1])*t0],p1=[a[0]+(b[0]-a[0])*t1,a[1]+(b[1]-a[1])*t1];pathSurface(g,p0,p1,path.width+5,mat('#bbb49f'),.04);pathSurface(g,p0,p1,path.width,mat('#3c4852',.94),.12);for(let along=15;along<len/steps;along+=30){const q=(t0*len+along)/len,x=a[0]+(b[0]-a[0])*q,z=a[1]+(b[1]-a[1])*q;dummy.position.set(x,terrainY(x,z)+.25,z);dummy.rotation.y=-Math.atan2(b[1]-a[1],b[0]-a[0]);dummy.updateMatrix();pathDashes.push(dummy.matrix.clone())}}}}
  if(pathDashes.length){const mesh=new THREE.InstancedMesh(boxGeometry(11,.12,.32),mats.line,pathDashes.length);pathDashes.forEach((m,i)=>mesh.setMatrixAt(i,m));g.add(mesh)}
  addRoadMedians(g,cx,cz);
 }
 function makeHouse(h){
  const g=new THREE.Group(),w=h.w,d=h.h,seed=String(h.id||`${h.x}:${h.y}`).split('').reduce((n,c)=>Math.imul(n^c.charCodeAt(0),16777619),2166136261),rand=seeded(seed),wallColors=['#e2d6c4','#d6c4a7','#e7dfcf','#d2c6b2','#cbb79a'],roofColors=['#975d44','#755044','#626864','#8c573f'],base=mat('#bba98d'),wall=mat(wallColors[Math.floor(rand()*wallColors.length)]),roof=mat(roofColors[Math.floor(rand()*roofColors.length)],.84),window=mat('#7faebb',.24,.08),trim=mat('#e9e2d6',.66,.12),drive=mat('#9c978a');
  flat(g,0,0,0,w+12,d+15,mat(h.style==='garden-estate'?'#89a978':'#9eaf87'));flat(g,0,.18,0,w+7,d+8,mats.concrete);flat(g,0,.2,-d*.5-5,w*.58,11,drive);box(g,0,.25,0,w,3.4,d,wall);box(g,0,3.35,0,w+.8,.25,d+.8,trim);
  const v=[-w/2,3.55,-d/2,w/2,3.55,-d/2,0,3.55+2.9,-d/2,-w/2,3.55,d/2,w/2,3.55,d/2,0,3.55+2.9,d/2],geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(v,3));geo.setIndex([0,1,2,3,5,4,0,3,4,0,4,1,1,4,5,1,5,2,2,5,3,2,3,0]);geo.computeVertexNormals();g.add(new THREE.Mesh(geo,roof));
  const frontGlass=mat('#83b8c4',.26,.12);for(const side of [-1,1])for(const x of [-w*.32,w*.32]){box(g,x,1.35,side*(d/2+.12),Math.min(4.5,w*.22),1.45,.22,window);box(g,x,1.35+((x>0)?0:0),side*(d/2+.25),.22,1.6,.14,trim)}
  for(const x of [-w*.42,w*.42])box(g,x,1.35,-d/2-.12,Math.min(3.5,w*.18),1.45,.2,window);
  box(g,0,.25,-d/2-.25,Math.max(2.2,w*.12),2.25,.38,mat('#604b3c'));flat(g,0,.12,-d/2-2,Math.min(w*.56,15),3.8,mat('#cfc6b6'));for(const x of [-w*.19,w*.19])box(g,x,.28,-d/2-2.7,.42,2.65,.42,trim);box(g,0,2.9,-d/2-2.55,Math.min(12,w*.62),.45,4.2,roof);
  // Each plot reads as its own small compound, with a gated wall, garden beds and a drive.
  const wallH=1.1,edgeZ=d/2+5,frontZ=-d/2-5;box(g,0,.2,edgeZ,w+10,wallH,.55,base);box(g,-w/2-5,.2,0,.55,wallH,d+10,base);box(g,w/2+5,.2,0,.55,wallH,d+10,base);for(const side of [-1,1])box(g,side*(w*.25+1),.2,frontZ,(w-6)/2,wallH,.55,base);for(const x of [-w/2-5,w/2+5])box(g,x,.25,frontZ,1.15,2.4,1.15,trim);
  for(let i=0;i<3;i++){const x=(i-1)*w*.31,z=d*.23,bed=new THREE.Mesh(new THREE.CylinderGeometry(2.1,2.5,.55,7),mat(i===1?'#657c4d':'#6c8151'));bed.position.set(x,.58,z);g.add(bed);const plant=new THREE.Mesh(new THREE.SphereGeometry(2.2,7,5),i%2?mats.leaf2:mats.leaf);plant.position.set(x,2.7,z);plant.scale.set(1,1.15,1);g.add(plant)}
  for(const x of [-w*.42,w*.42]){box(g,x,1.3,d/2+1.3,.25,2.2,.25,base);box(g,x,1.5,d/2+2.7,2.1,.12,2.7,roof)}return g;
 }
 function houseRoofGeometry(){const g=new THREE.BufferGeometry(),p=[-.5,0,-.5,.5,0,-.5,0,1,-.5,-.5,0,.5,.5,0,.5,0,1,.5];g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setIndex([0,1,2,3,5,4,0,3,4,0,4,1,1,4,5,1,5,2]);g.computeVertexNormals();sharedGeometry.add(g);return g}
 const distantHouseRoof=houseRoofGeometry();
 function addHomes(group,homes){if(!homes.length)return;const bodies=new THREE.InstancedMesh(boxGeometry(23.5,3.4,18.5),mat('#ffffff'),homes.length),roofs=new THREE.InstancedMesh(distantHouseRoof,mat('#ffffff',.83),homes.length),items=[],dummy=new THREE.Object3D();bodies.castShadow=false;roofs.castShadow=false;
  homes.forEach((h,i)=>{const x=h.x+h.w/2,z=h.y+h.h/2,ground=terrainY(x,z);dummy.position.set(x,ground+1.95,z);dummy.scale.set(h.w/23.5,1,h.h/18.5);dummy.updateMatrix();bodies.setMatrixAt(i,dummy.matrix);dummy.position.set(x,ground+3.5,z);dummy.scale.set(h.w+4,1.35,h.h+4);dummy.updateMatrix();roofs.setMatrixAt(i,dummy.matrix);bodies.setColorAt(i,color(h.style==='garden-estate'?'#e3d5bd':'#d3bea0'));roofs.setColorAt(i,color(h.style==='garden-estate'?'#905642':'#8b5140'));items.push({h,x,z,ground,detail:null,parent:group,near:false,index:i})});group.add(bodies,roofs);group.userData.homeLOD={bodies,roofs,items};}
 function dummyHome(item,bodies,roofs){const d=new THREE.Object3D(),scale=item.near?0:1;d.position.set(item.x,item.ground+1.95,item.z);d.scale.set(item.h.w/23.5*scale,scale,item.h.h/18.5*scale);d.updateMatrix();bodies.setMatrixAt(item.index,d.matrix);d.position.set(item.x,item.ground+3.5,item.z);d.scale.set((item.h.w+4)*scale,1.35*scale,(item.h.h+4)*scale);d.updateMatrix();roofs.setMatrixAt(item.index,d.matrix)}
 function buildCityFabric(group,lots,cx,cz){
  if(!lots?.length)return;
  const cube=boxGeometry(1,1,1),floorsOf=b=>clamp(b.floors||2,1,24),windowCapacity=lots.reduce((n,b)=>{const cols=Math.max(2,Math.ceil(b.w/14)),rows=Math.max(2,Math.ceil(b.h/14));return n+floorsOf(b)*2*(cols+rows)},0),bandCapacity=lots.reduce((n,b)=>n+Math.max(0,floorsOf(b)-1)*2,0),balconyCapacity=lots.reduce((n,b)=>n+((b.type==='apartment'||b.type==='villa'||b.type==='house'||floorsOf(b)>=8)?4:0),0);
  const white=mat('#ffffff',.76),bodyLow=new THREE.InstancedMesh(cube,white,lots.length),bodyTower=new THREE.InstancedMesh(cube,white,lots.length),roof=new THREE.InstancedMesh(cube,white,lots.length),parapets=new THREE.InstancedMesh(cube,white,lots.length*4),bands=new THREE.InstancedMesh(cube,white,Math.max(1,bandCapacity)),fins=new THREE.InstancedMesh(cube,white,lots.length*4),windowFrames=new THREE.InstancedMesh(cube,mat('#d6d2c6',.58,.12),windowCapacity),windowsOn=new THREE.InstancedMesh(cube,mats.windowLit,windowCapacity),windowsOff=new THREE.InstancedMesh(cube,mats.windowDark,windowCapacity),balconies=new THREE.InstancedMesh(cube,mat('#a4a49b',.66,.22),Math.max(1,balconyCapacity)),balconyRails=new THREE.InstancedMesh(cube,mat('#47545a',.46,.38),Math.max(1,balconyCapacity)),awnings=new THREE.InstancedMesh(cube,white,lots.length),units=new THREE.InstancedMesh(cube,mat('#a8a397',.86),lots.length*2),dummy=new THREE.Object3D();
  for(const mesh of [bodyLow,bodyTower,roof,parapets,bands,fins,windowFrames,windowsOn,windowsOff,balconies,balconyRails,awnings,units])mesh.castShadow=false;
  const cityPalettes={residential:['#ddcfb7','#c9b79d','#e7ded0','#d5c6ae','#bba98f'],office:['#aebac0','#7e9299','#c7cbca','#66777f','#d6d4ca'],shop:['#d4c4a8','#bdab8e','#d9d3c5','#c8b497','#9faeb0'],warehouse:['#aaa9a1','#c1baaa','#8e9a99','#bcb7a9'],institution:['#ddd6c7','#c9c1b1','#aaa99e','#e5dfd2']},roofPalette=['#3e484c','#755044','#59666a','#8d7457','#465762'],facadeTrim=['#e8dfcd','#d2c8b5','#a9b7b7','#c3a97e'];
  let frameIndex=0,onIndex=0,offIndex=0,bandIndex=0,finIndex=0,parapetIndex=0,balconyIndex=0,awningIndex=0,unitIndex=0;
  lots.forEach((b,i)=>{
   const rand=seeded(b.seed),x=b.x+b.w/2,z=b.y+b.h/2,ground=terrainY(x,z),floors=floorsOf(b),floorH=3.65,height=floors*floorH,w=b.w,d=b.h,residential=b.type==='villa'||b.type==='house'||b.type==='apartment'||b.style.includes('residential')||b.style.includes('estate'),institution=['government','bank','hospital','university'].includes(b.type)||b.style==='modern-civic',palette=residential?cityPalettes.residential:institution?cityPalettes.institution:b.type==='warehouse'?cityPalettes.warehouse:b.type==='office'||floors>=7?cityPalettes.office:cityPalettes.shop,primary=palette[Math.floor(rand()*palette.length)],upperColor=palette[Math.floor(rand()*palette.length)],roofColor=roofPalette[residential?1:(b.roof||0)%roofPalette.length],trimColor=facadeTrim[Math.floor(rand()*facadeTrim.length)],highrise=floors>=7&&!residential&&b.type!=='warehouse',baseFloors=highrise?3:floors,baseHeight=baseFloors*floorH,upperFloors=floors-baseFloors,towerW=highrise?w*(.72+rand()*.12):w,towerD=highrise?d*(.7+rand()*.16):d,towerX=highrise?(rand()-.5)*w*.13:0,towerZ=highrise?d*.07:0;
   dummy.position.set(x,ground+baseHeight/2,z);dummy.scale.set(w,baseHeight,d);dummy.rotation.set(0,0,0);dummy.updateMatrix();bodyLow.setMatrixAt(i,dummy.matrix);bodyLow.setColorAt(i,color(primary));
   if(highrise){dummy.position.set(x+towerX,ground+baseHeight+(height-baseHeight)/2,z+towerZ);dummy.scale.set(towerW,height-baseHeight,towerD);dummy.updateMatrix();bodyTower.setMatrixAt(i,dummy.matrix);bodyTower.setColorAt(i,color(upperColor))}else{dummy.position.set(0,-10000,0);dummy.scale.set(0,0,0);dummy.updateMatrix();bodyTower.setMatrixAt(i,dummy.matrix);bodyTower.setColorAt(i,color(primary))}
   const roofW=highrise?towerW:w,roofD=highrise?towerD:d,roofX=x+towerX,roofZ=z+towerZ;dummy.position.set(roofX,ground+height+.36,roofZ);dummy.scale.set(roofW+2.6,.72,roofD+2.6);dummy.updateMatrix();roof.setMatrixAt(i,dummy.matrix);roof.setColorAt(i,color(roofColor));
   const parapetH=highrise?1.1:.72;for(const side of [-1,1]){dummy.position.set(roofX,ground+height+parapetH/2,roofZ+side*(roofD/2+1));dummy.scale.set(roofW+2,parapetH,.42);dummy.updateMatrix();parapets.setMatrixAt(parapetIndex++,dummy.matrix);parapets.setColorAt(parapetIndex-1,color(trimColor));dummy.position.set(roofX+side*(roofW/2+1),ground+height+parapetH/2,roofZ);dummy.scale.set(.42,parapetH,roofD+2);dummy.updateMatrix();parapets.setMatrixAt(parapetIndex++,dummy.matrix);parapets.setColorAt(parapetIndex-1,color(trimColor))}
   // Rooftop water tanks and HVAC boxes break up the repeated roof silhouette.
   for(let k=0;k<2;k++){const ux=roofX+(rand()-.5)*roofW*.48,uz=roofZ+(rand()-.5)*roofD*.42;dummy.position.set(ux,ground+height+1.2+k*.35,uz);dummy.scale.set(k===0?Math.min(5,w*.14):Math.min(3.2,w*.1),k===0?2.4:1.35,k===0?Math.min(4,d*.15):Math.min(3,d*.1));dummy.updateMatrix();units.setMatrixAt(unitIndex++,dummy.matrix);units.setColorAt(unitIndex-1,color(k===0?'#9b9b8c':'#768187'))}
   const faces=[];
   for(let f=0;f<floors;f++){
    const upper=highrise&&f>=baseFloors,fw=upper?towerW:w,fd=upper?towerD:d,fx=x+(upper?towerX:0),fz=z+(upper?towerZ:0),fy=ground+f*floorH+1.95,cols=Math.max(2,Math.ceil(fw/14)),rows=Math.max(2,Math.ceil(fd/14)),windowW=Math.min(4.1,(fw-10)/cols*.55),windowD=Math.min(4.1,(fd-10)/rows*.55),windowH=1.7;
    for(let c=0;c<cols;c++){const wx=fx-fw/2+5+(c+.5)*(fw-10)/cols;for(const side of [-1,1])faces.push([wx,fy,fz+side*(fd/2+.23),windowW,windowH,.32,rand()>.31,true])}
    for(let c=0;c<rows;c++){const wz=fz-fd/2+5+(c+.5)*(fd-10)/rows;for(const side of [-1,1])faces.push([fx+side*(fw/2+.23),fy,wz,.32,windowH,windowD,rand()>.31,false])}
    if(f>0){const by=ground+f*floorH;dummy.position.set(fx,by,fz-fd/2-.33);dummy.scale.set(fw,.2,.36);dummy.updateMatrix();bands.setMatrixAt(bandIndex,dummy.matrix);bands.setColorAt(bandIndex++,color(trimColor));dummy.position.set(fx+fw/2+.33,by,fz);dummy.scale.set(.36,.2,fd);dummy.updateMatrix();bands.setMatrixAt(bandIndex,dummy.matrix);bands.setColorAt(bandIndex++,color(trimColor))}
    if(residential&&f>0&&balconyIndex<balconyCapacity&&((!highrise&&f<=2)||(highrise&&f%2===0))){const bx=fx+(f%2?-.18:.18)*fw,bz=fz-fd/2-1.45,bw=Math.min(7.5,fw*.34);dummy.position.set(bx,ground+f*floorH+.3,bz);dummy.scale.set(bw,.32,2.8);dummy.updateMatrix();balconies.setMatrixAt(balconyIndex,dummy.matrix);dummy.position.set(bx,ground+f*floorH+1,bz-1.22);dummy.scale.set(bw,.78,.18);dummy.updateMatrix();balconyRails.setMatrixAt(balconyIndex++,dummy.matrix)}
   }
   // Recessed framed glazing, rather than painted-on window squares.
   for(const [wx,wy,wz,ww,wh,wd,lit,frontFace] of faces){const offsetX=frontFace?0:Math.sign(wx-x)*.19,offsetZ=frontFace?Math.sign(wz-z)*.19:0;dummy.position.set(wx,wy,wz);dummy.scale.set(frontFace?ww+.62:.32,wh+.62,frontFace?.32:wd+.62);dummy.updateMatrix();windowFrames.setMatrixAt(frameIndex,dummy.matrix);dummy.position.set(wx+offsetX,wy,wz+offsetZ);dummy.scale.set(frontFace?ww:.13,wh,frontFace?.13:wd);dummy.updateMatrix();if(lit)windowsOn.setMatrixAt(onIndex++,dummy.matrix);else windowsOff.setMatrixAt(offIndex++,dummy.matrix);frameIndex++}
   // Four subtle vertical piers and a deep shop canopy give each block a legible facade.
   const featureW=highrise?towerW:w,featureD=highrise?towerD:d,featureX=x+towerX,featureZ=z+towerZ;for(const sx of [-1,1])for(const sz of [-1,1]){dummy.position.set(featureX+sx*(featureW/2+.2),ground+height/2,featureZ+sz*(featureD/2+.2));dummy.scale.set(.36,height,.36);dummy.updateMatrix();fins.setMatrixAt(finIndex,dummy.matrix);fins.setColorAt(finIndex++,color(trimColor))}
   if(['shop','market','restaurant','retail','club','hotel'].includes(b.type)){dummy.position.set(x,ground+3.65,z-d/2-1.05);dummy.scale.set(Math.min(w*.86,52),.62,2.4);dummy.updateMatrix();awnings.setMatrixAt(awningIndex,dummy.matrix);awnings.setColorAt(awningIndex++,color(['#bc8052','#637f84','#b88d55','#9b6b5d'][Math.floor(rand()*4)]))}
  });
  for(const mesh of [bodyLow,bodyTower,roof,parapets,bands,fins,windowFrames,windowsOn,windowsOff,balconies,balconyRails,awnings,units])mesh.instanceMatrix.needsUpdate=true;
  for(const mesh of [bodyLow,bodyTower,roof,parapets,bands,fins,units,awnings])if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;
  parapets.count=parapetIndex;bands.count=bandIndex;fins.count=finIndex;windowFrames.count=frameIndex;windowsOn.count=onIndex;windowsOff.count=offIndex;balconies.count=balconyIndex;balconyRails.count=balconyIndex;awnings.count=awningIndex;units.count=unitIndex;
  group.add(bodyLow,bodyTower,roof,parapets,bands,fins,windowFrames,windowsOff,windowsOn,balconies,balconyRails,awnings,units);
 }
 function roundaboutAsset(group,r){const x=r.x,z=r.y,ground=terrainY(x,z),radius=r.radius||42,asphalt=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,.22,28),mats.road);asphalt.position.set(x,ground+.14,z);group.add(asphalt);const island=new THREE.Mesh(new THREE.CylinderGeometry(radius*.56,radius*.56,1.2,24),mats.park);island.position.set(x,ground+.72,z);group.add(island);const curb=new THREE.Mesh(new THREE.TorusGeometry(radius*.58,1.15,5,28),mats.roadEdge);curb.rotation.x=-Math.PI/2;curb.position.set(x,ground+1.36,z);group.add(curb);const lane=new THREE.InstancedMesh(boxGeometry(4,.12,.5),mats.white,20);for(let i=0;i<20;i++){const a=i/20*Math.PI*2;dummyRoundabout.position.set(x+Math.cos(a)*radius*.79,ground+.3,z+Math.sin(a)*radius*.79);dummyRoundabout.rotation.y=-a;dummyRoundabout.updateMatrix();lane.setMatrixAt(i,dummyRoundabout.matrix)}group.add(lane);for(let i=0;i<5;i++){const a=i/5*Math.PI*2,tx=x+Math.cos(a)*radius*.25,tz=z+Math.sin(a)*radius*.25;const shrub=new THREE.Mesh(new THREE.DodecahedronGeometry(2.8,0),mats.leaf2);shrub.position.set(tx,ground+3.5,tz);group.add(shrub)}if(r.monument){const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(4,5,3,8),mats.concrete);pedestal.position.set(x,ground+2.8,z);group.add(pedestal);const spire=new THREE.Mesh(new THREE.ConeGeometry(2.2,12,7),mat('#d8ae4f',.46,.26));spire.position.set(x,ground+10,z);group.add(spire)} }
 const dummyRoundabout=new THREE.Object3D();
 function constructionSite(group,b){const lotW=188,lotD=152,site=new THREE.Group();site.position.set(b.x+b.w/2,terrainY(b.x,b.y),b.y+b.h/2);flat(site,0,.1,0,lotW,lotD,mat('#b58e5e'));flat(site,0,.32,0,lotW-12,lotD-12,mat('#c3a06a'));
  const fence=mat('#175968');for(const z of [-lotD/2+4,lotD/2-4])for(let x=-lotW/2+4;x<=lotW/2-4;x+=8){if(z>0&&Math.abs(x)<18)continue;box(site,x,.35,z,.65,2.4,.65,fence)}
  for(const x of [-lotW/2+4,lotW/2-4])for(let z=-lotD/2+4;z<=lotD/2-4;z+=8)box(site,x,.35,z,.65,2.4,.65,fence);
  for(const z of [-lotD/2+4,lotD/2-4]){const gap=z>0?18:0,start=-lotW/2+7,end=lotW/2-7;for(let x=start;x<end;x+=8){if(z>0&&x>=-gap&&x<=gap)continue;box(site,x+4,1,z,8,.18,.28,mat('#3c7881'));box(site,x+4,1.8,z,8,.16,.28,mat('#568a89'))}}
  for(const x of [-lotW/2+4,lotW/2-4])for(const z of [-lotD/2+8,0,lotD/2-8]){box(site,x,2.8,z,1,3,1,mat('#c7b087'));const lamp=new THREE.PointLight('#ffe2a7',18,20);lamp.position.set(x,6,z);site.add(lamp)}
  const bw=78,bd=58,floor=4.1;flat(site,0,.55,0,bw+7,bd+7,mat('#777a74'));
  for(let level=0;level<5;level++){
   const y=.8+level*floor;flat(site,0,y,0,bw,bd,mat(level===4?'#858981':'#969a92'));
   for(const x of [-bw/2+2,bw/2-2])for(const z of [-bd/2+2,bd/2-2])box(site,x,y,z,1.15,floor,.95,mat('#b2b2a8'));
   for(const x of [-bw/2+2,0,bw/2-2])for(const z of [-bd/2+2,bd/2-2])box(site,x,y,z,.95,floor,.95,mat('#aaa99f'));
   if(level===1||level===2){box(site,-bw*.29,y+1,-bd/2, bw*.37,2,1.1,mat('#768780'));box(site,bw*.3,y+1,bd*.18,bw*.3,2,1.1,mat('#667b82'))}
  }
  const scaffold=mat('#b36636');for(const z of [-bd/2-3,bd/2+3])for(let x=-bw/2-4;x<=bw/2+4;x+=7){box(site,x,.8,z,.3,18,.3,scaffold);for(let y=4;y<18;y+=4)box(site,x,y,z,6,.22,.22,scaffold)}
  for(let y=4;y<20;y+=4)for(let x=-bw/2-4;x<bw/2+4;x+=14)box(site,x+7,y,-bd/2-3,13,.18,.18,scaffold);
  for(const x of [-bw*.32,-bw*.04,bw*.3])for(let i=0;i<3;i++){box(site,x+i*.75,20,bd*.24,.16,3,.16,mat('#776c59'));box(site,x-.5,22,bd*.24,1.3,.16,.16,mat('#776c59'))}
  // A 50 m tower crane with lattice jib, hoist cable, operator cab and hook.
  const craneX=-lotW*.31,craneZ=-lotD*.18,crane=mat('#d2a12e');for(const x of [-1.3,1.3])for(const z of [-1.3,1.3])box(site,craneX+x,.4,craneZ+z,.28,48,.28,crane);
  for(let y=3;y<48;y+=4){for(const z of [-1.3,1.3]){const brace=box(site,craneX,y,z,2.1,.2,.2,crane);brace.rotation.z=.63;const other=box(site,craneX,y+1.7,z,2.1,.2,.2,crane);other.rotation.z=-.63}}
  box(site,craneX,48,craneZ,5,1,4,mat('#8a692f'));box(site,craneX,49,craneZ,6,1.1,5,mat('#9bb4b7'));
  for(const x of [-43,43])box(site,craneX+x,50,craneZ,1,1,1,crane);for(let x=-42;x<44;x+=7){box(site,craneX+x,51,craneZ,7,.4,.36,crane);const diagonal=box(site,craneX+x+3.5,51,craneZ,7,.22,.22,crane);diagonal.rotation.z=x%14?-.5:.5}
  box(site,craneX-27,50,craneZ,18,1,2.5,crane);box(site,craneX-27,51,craneZ,1,.4,3,crane);
  const cable=box(site,craneX+20,29,craneZ,.12,21,.12,mat('#343a39'));box(site,craneX+20,18,craneZ,.5,1.5,.5,mat('#232829'));
  // Rebar cage, site hoist, concrete mixer and stacked materials.
  for(let i=0;i<9;i++)box(site,-26+i*6,.9,bd*.37,4,1.5,3,mat(i%2?'#9a704c':'#bd9568'));
  for(const x of [-35,35])for(const z of [-20,0,20]){box(site,x,.8,z,1,7,1,mat('#6d5140'));box(site,x,4.5,z,3,.35,3,mat('#b48a57'))}
  carModel(site,-61,.0,'#c24d3f','bus');const tag=label('BUILDING SITE · UNDER CONSTRUCTION','#f4ead8','#37362f',15);tag.scale.set(58,11,1);tag.position.set(0,6,lotD/2+5);site.add(tag);group.add(site);return site;
 }
 function estateEntrance(group,b){const g=new THREE.Group(),w=42,d=22;g.position.set(b.x+b.w/2,terrainY(b.x,b.y),b.y+b.h/2);flat(g,0,.1,0,w,d,mats.concrete);box(g,-13,.2,0,4,6,5,mat('#b7a07a'));box(g,13,.2,0,4,6,5,mat('#b7a07a'));box(g,0,6,0,30,1,5,mat('#eee8d9'));box(g,0,6,-1,24,2,.6,mat('#263541'));const sign=label(b.name.toUpperCase(),'#202832','#f7edcf',16);sign.scale.set(29,6,1);sign.position.set(0,8,-3);g.add(sign);box(g,0,.3,8,2,2.5,2,mat('#d1c3a8'));const arm=box(g,0,2,3,13,.35,.45,mat('#f0ead9'));arm.rotation.y=.12;g.add(arm);group.add(g)}
 function parkAsset(group,b){const g=new THREE.Group(),w=b.w+85,d=b.h+75;g.position.set(b.x+b.w/2,terrainY(b.x,b.y),b.y+b.h/2);flat(g,0,.1,0,w,d,mat('#7fa976'));flat(g,0,.26,0,w-16,d-16,mat('#a9bf8f'));for(let x=-w*.36;x<w*.4;x+=w*.24)rect(g,x,0,4,d*.76,mat('#d3c7a6'));const water=new THREE.Mesh(new THREE.CylinderGeometry(7,7,.5,18),mat('#5caec1',.22));water.position.set(0,.6,0);g.add(water);const fountain=new THREE.Mesh(new THREE.CylinderGeometry(1.2,1.2,3,10),mat('#d3d1c6'));fountain.position.set(0,2,0);g.add(fountain);const labelMesh=label(b.name);labelMesh.position.set(0,14,-d*.48);g.add(labelMesh);group.add(g)}
 function rockFormation(group,b){const cx=b.x+b.w/2,cz=b.y+b.h/2,random=seeded(5400),segments=12,levels=[0,27,92,177,258,315],radii=[148,142,119,91,53,15],vertices=[],indices=[],geometry=new THREE.BufferGeometry();for(let k=0;k<levels.length;k++){for(let i=0;i<segments;i++){const a=i/segments*Math.PI*2,jitter=.84+random()*.32,x=cx+Math.cos(a)*radii[k]*jitter,z=cz+Math.sin(a)*radii[k]*.76*jitter;vertices.push(x,terrainY(x,z)+levels[k],z)}}for(let k=0;k<levels.length-1;k++)for(let i=0;i<segments;i++){const a=k*segments+i,b0=k*segments+(i+1)%segments,c=(k+1)*segments+i,d=(k+1)*segments+(i+1)%segments;indices.push(a,c,b0,b0,c,d)}geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setIndex(indices);geometry.computeVertexNormals();const tones=[mat('#514f48',.98),mat('#615d54',.96),mat('#716b5f',.95),mat('#4c514c',.98),mat('#837969',.94)];for(let k=0;k<levels.length-1;k++)geometry.addGroup(k*segments*6,segments*6,k%tones.length);group.add(new THREE.Mesh(geometry,tones));
  const boulderGeo=new THREE.DodecahedronGeometry(12,0),boulders=new THREE.InstancedMesh(boulderGeo,tones[0],18),dummy=new THREE.Object3D();for(let i=0;i<18;i++){const a=random()*Math.PI*2,r=95+random()*70,x=cx+Math.cos(a)*r,z=cz+Math.sin(a)*r*.76;dummy.position.set(x,terrainY(x,z)+7+random()*6,z);dummy.rotation.set(random()*.25,random()*6.28,random()*.25);dummy.scale.set(.8+random()*1.4,.75+random()*1.6,.7+random()*1.3);dummy.updateMatrix();boulders.setMatrixAt(i,dummy.matrix)}group.add(boulders);
  const path=rect(group,cx,cz+139,b.w*.72,4,mat('#c2a980'));path.rotation.y=-.18;const plaque=label('ASO ROCK  ·  ABUJA','#303432','#f5eddd',20);plaque.scale.set(45,9,1);plaque.position.set(cx,terrainY(cx,cz)+91,cz-b.h*.44);group.add(plaque)}
 function showroomModel(){const g=new THREE.Group(),w=G.world.carDealership.showroom.w,d=G.world.carDealership.showroom.d,h=13.2,charcoal=mat('#22272b',.34,.34),black=mat('#171b1f',.36,.28),glass=new THREE.MeshStandardMaterial({color:'#c1e3e7',roughness:.18,metalness:.06,transparent:true,opacity:.4,depthWrite:false}),stone=mat('#c5baa6',.82),metal=mat('#50575b',.46,.52);customMaterials.push(glass);
  flat(g,0,.05,0,w+8,d+8,stone);box(g,0,.35,d/2-1,w,h-1.2,2.6,charcoal);box(g,-w/2+1,.3,0,2,h,d,charcoal);box(g,w/2-1,.3,0,2,h,d,charcoal);
  for(let floor=0;floor<2;floor++){const y=.65+floor*5.4;box(g,0,y,-d/2+.24,w-4,4.3,.48,glass);box(g,0,y+4.42,-d/2+.15,w+1,.46,.64,metal);for(let x=-w/2+4;x<w/2-2;x+=7.4)box(g,x,y,-d/2-.15,.38,4.45,.4,black);box(g,0,y+2.1,-d/2-.18,w-3,.22,.26,metal)}
  for(let x of [-w/2+2,w/2-2])box(g,x,.35,-d/2-1.1,1,10.2,1.05,stone);
  box(g,0,11.1,-d/2,w+4,.5,d+2,charcoal);box(g,0,12.7,0,w+5,.55,d+3,black);box(g,0,13.25,0,w+1,.35,d+1,metal);
  box(g,0,.35,-d/2-.75,8,2.5,.3,glass);box(g,0,.35,-d/2-2,28,.42,8,charcoal);for(const x of [-13,-6,6,13])box(g,x,.45,-d/2-2,.24,3.6,.24,metal);
  const reception=box(g,0,.55,d*.15,w*.28,.85,2.1,stone);reception.material=mat('#d0c6b3');
   for(const [i,x] of [-53,-18,17,52].entries()){const car=carModel(g,x,-d*.13,['#151a20','#d0d5d5','#a83b34','#36495a'][i],i===2?'sport':i===1?'sedan':'suv',false,true);car.rotation.y=x===17?.16:-.12}
   const sign=label('ABUJACAR  ·  CAR DEALERSHIP','#11161c','#fff5df',31);sign.scale.set(72,13,1);sign.position.set(0,10.1,-d/2-.7);g.add(sign);
  return g}
 function dealership(group,b){const root=new THREE.Group(),lot=G.world.carDealership.lot;root.position.set(lot.x+lot.w/2,terrainY(lot.x+lot.w/2,lot.y+lot.h/2),lot.y+lot.h/2);root.rotation.y=Number(b.rotation)||0;root.scale.setScalar(Number(b.scale)||1);
  flat(root,0,.1,0,lot.w,lot.h,mat('#42494d'));flat(root,0,.34,0,lot.w-8,lot.h-8,mat('#686967'));flat(root,0,.38,lot.h/2+10,lot.w-12,25,mat('#777a76'));
  const fence=mat('#202a2e',.58,.36),post=mat('#a99d86');for(let i=0;i<4;i++){const side=i<2?'z':'x',sgn=i%2?1:-1,alongX=side==='z',length=alongX?lot.w:lot.h;for(let p=-length/2+4;p<length/2-4;p+=7){const fx=alongX?p:sgn*(lot.w/2-3),fz=alongX?sgn*(lot.h/2-3):p;if(alongX&&sgn<0&&Math.abs(fx)<lot.gateWidth/2+2)continue;box(root,fx,.4,fz,.55,2.4,.55,fence);if(p+7>=length/2-4)break}const railCount=Math.ceil(length/5);for(let j=0;j<railCount;j++){const p=-length/2+2+j*5,fx=alongX?p:sgn*(lot.w/2-3),fz=alongX?sgn*(lot.h/2-3):p;if(alongX&&sgn<0&&Math.abs(fx)<lot.gateWidth/2+2)continue;box(root,fx,1.1,fz,alongX?5:.18,.16,alongX?.18:5,fence);box(root,fx,2,fz,alongX?5:.16,.14,alongX?.16:5,fence)} }
  const showroom=G.world.carDealership.showroom,model=showroomModel();model.position.set(showroom.x-lot.x-lot.w/2,.42,showroom.y-lot.y-lot.h/2);root.add(model);
  const sb=G.world.carDealership.workshop,sx=sb.x-lot.x-lot.w/2,sz=sb.y-lot.y-lot.h/2;box(root,sx,.4,sz,24,8,38,mat('#373e41'));box(root,sx,.5,sz-19.4,18,5,1.1,mat('#697276'));for(const x of [sx-7,sx+7])box(root,x,.45,sz-20.2,.35,5.6,.35,post);const workSign=label('SERVICE BAY','#263239','#efe9db',15);workSign.scale.set(20,4,1);workSign.position.set(sx,7,sz-20.7);root.add(workSign);
   const boothX=-lot.w/2+17,boothZ=-lot.h/2+17;box(root,boothX,.4,boothZ,10,3.8,8,mat('#d2c6b1'));box(root,boothX,.95,boothZ-4.08,7,1.7,.18,mat('#8ec2ce',.23,.08));box(root,-7,.7,-lot.h/2+3,14,.42,1,mat('#f0dfad'));box(root,7,.7,-lot.h/2+3,14,.42,1,mat('#f0dfad'));box(root,-7,2.2,-lot.h/2+4.2,16,.2,.2,mat('#242a2b'));box(root,7,2.2,-lot.h/2+4.2,16,.2,.2,mat('#242a2b'));const inLabel=label('IN  →','#202832','#f4c448',18),outLabel=label('OUT  ←','#202832','#f4c448',18);inLabel.scale.set(16,4,1);outLabel.scale.set(18,4,1);inLabel.position.set(-7,4.2,-lot.h/2+3);outLabel.position.set(7,4.2,-lot.h/2+3);root.add(inLabel,outLabel);for(const [x,rotation] of [[-7,.15],[7,-.15]]){const arm=box(root,x,2.5,-lot.h/2+9,10,.28,.35,mat('#f2ece0'));arm.rotation.y=rotation}
  const cars=G.world.carDealership.cars||[];cars.forEach((c,i)=>{const px=c.x-lot.x-lot.w/2,pz=c.y-lot.y-lot.h/2;carModel(root,px,pz,c.color,c.kind,false,true);if(!c.interior){const yellow=mat('#e5b347');for(const side of [-1,1])box(root,px+side*4.6,.39,pz, .12,.045,8,yellow);if(i<2)box(root,px,.39,pz+4,.12,.045,8,yellow)}});
   for(const x of [-105,-35,35,105]){const z=lot.h*.18;for(const dx of [-16,16])box(root,x+dx,.36,z,.24,.06,38,mat('#565e61'));for(const dz of [-14,14])box(root,x,.36,z+dz,30,.06,.24,mat('#565e61'));box(root,x,.4,z+31,25,.08,10,mat('#68645b'));for(const dx of [-16,16])for(const dz of [-13,13])box(root,x+dx,.38,z+dz,.2,5.9,.2,mat('#50575b',.46,.52));box(root,x,6.5,z,35,.5,31,mat('#737a7b',.48,.3));box(root,x,6.08,z,35,.16,31,mat('#484f53',.62,.35))}
  for(const x of [-lot.w/2+17,lot.w/2-17]){for(const z of [-lot.h/2+12,lot.h/2-12]){box(root,x,.3,z,2.5,5,2.5,mat('#283238'));const lamp=new THREE.PointLight('#ffd38a',22,42);lamp.position.set(x,7,z);root.add(lamp)}}
   for(let i=0;i<12;i++){const x=-lot.w/2+14+i*30,z=i%2?-lot.h/2+12:lot.h/2-12;box(root,x,.32,z,.7,7,.7,mats.trunk);for(let arm=0;arm<5;arm++){const leaf=new THREE.Mesh(new THREE.ConeGeometry(1.15,7,5),mats.leaf2);leaf.position.set(x+Math.cos(arm*Math.PI*2/5)*3,7.6+Math.sin(arm*Math.PI*2/5)*1.2,z+Math.sin(arm*Math.PI*2/5)*3);leaf.rotation.z=.8;leaf.rotation.x=.5;root.add(leaf)}}
  root.userData.type='dealer';group.add(root);return root;
  }
 function carStand(group,b){const w=Math.max(168,b.w+52),d=Math.max(132,b.h+40),root=new THREE.Group(),ground=terrainY(b.x+b.w/2,b.y+b.h/2);root.position.set(b.x+b.w/2,ground,b.y+b.h/2);flat(root,0,.05,0,w,d,mat('#3e484b'));flat(root,0,.22,0,w-8,d-8,mat('#70716b'));flat(root,0,.38,d*.25,w-16,d*.35,mat('#50585a'));
  const facade=mat('#343b3e',.42,.35),glass=new THREE.MeshStandardMaterial({color:'#a9d4d8',roughness:.2,metalness:.08,transparent:true,opacity:.54}),sign=label(b.name.toUpperCase(),'#171b1e','#f7df9b',24);customMaterials.push(glass);box(root,0,.55,-d*.29,w*.72,13,d*.22,facade);box(root,0,1.4,-d*.405,w*.65,8,.3,glass);for(let x=-w*.34;x<=w*.34;x+=w*.17)box(root,x,1.5,-d*.41,.45,8,.45,mat('#242a2d',.45,.25));box(root,0,13.7,-d*.29,w*.75,.8,d*.24,mat('#202528',.45,.3));sign.scale.set(w*.52,12,1);sign.position.set(0,10.5,-d*.42);root.add(sign);
  for(const [i,x] of [-w*.3,-w*.1,w*.1,w*.3].entries()){const z=d*.03;for(const dx of [-13,13])box(root,x+dx,.38,z,.22,.08,27,mat('#d6b04d'));for(const dz of [-11,11])box(root,x,.38,z+dz,25,.08,.22,mat('#d6b04d'));box(root,x,7.2,z,28,.5,25,mat(i%2?'#535b5e':'#747877',.42,.28));for(const dx of [-13,13])for(const dz of [-11,11])box(root,x+dx,.4,z+dz,.28,6.8,.28,mat('#4c5558',.45,.4));box(root,x,6.9,z,28,.42,25,mat('#647174',.34,.34));}
  const kinds=['suv','sedan','sport','suv','sedan','suv'],paints=['#151a20','#e0ded6','#a53931','#455866','#d0ad6b','#192a37'];kinds.forEach((kind,i)=>{const x=(i%3-1)*w*.27,z=i<3?-d*.02:d*.34;carModel(root,x,z,paints[i],kind,false,true)});
  for(const x of [-w*.45,w*.45])for(const z of [-d*.38,d*.38]){box(root,x,.3,z,1,6,1,mat('#30393b'));const lamp=new THREE.PointLight('#ffd28c',14,34);lamp.position.set(x,7,z);root.add(lamp)}
  box(root,-w*.34,.2,d*.44,2,4,2,mat('#a99d86'));box(root,w*.34,.2,d*.44,2,4,2,mat('#a99d86'));const gate=label('SALES  ·  BUY  ·  SELL  ·  TRADE-IN','#20262a','#f3d88e',16);gate.scale.set(40,8,1);gate.position.set(0,3,d*.47);root.add(gate);group.add(root);return root}
 function restaurantProperty(group,b){const w=Math.max(104,b.w+38),d=Math.max(82,b.h+34),root=new THREE.Group();root.position.set(b.x+b.w/2,terrainY(b.x+b.w/2,b.y+b.h/2),b.y+b.h/2);const club=b.type==='club',wall=mat(club?'#29343d':'#8a6b50',.68,.08),roof=mat(club?'#25313b':'#393f3e',.48,.2),glass=new THREE.MeshStandardMaterial({color:club?'#a7d5da':'#f4ca7f',roughness:.2,metalness:.04,emissive:'#f4a74a',emissiveIntensity:.34,transparent:true,opacity:.72});customMaterials.push(glass);flat(root,0,.04,0,w,d,mat('#c9b68e'));flat(root,0,.24,-d*.05,w-6,d*.82,mat('#ddd0b9'));box(root,0,.4,-d*.18,w*.76,8,d*.48,wall);box(root,0,4.6,-d*.426,w*.68,4.9,.32,glass);for(let x=-w*.31;x<=w*.31;x+=w*.155)box(root,x,4.6,-d*.44,.42,5.2,.5,mat('#352f2b'));
  box(root,0,9,-d*.17,w*.82,.8,d*.55,roof);for(const x of [-w*.37,w*.37])box(root,x,.4,-d*.17,1,9,1,mat('#c4ad87'));const sign=label(b.name.toUpperCase(),club?'#24303b':'#362a25','#ffe7b1',22);sign.scale.set(Math.min(75,w*.66),11,1);sign.position.set(0,8,-d*.47);root.add(sign);
  const patioZ=d*.29;flat(root,0,.26,patioZ,w*.86,d*.3,mat('#b8996e'));for(let x=-w*.32;x<=w*.32;x+=w*.32){for(let z of [patioZ-d*.08,patioZ+d*.08]){const table=new THREE.Mesh(new THREE.CylinderGeometry(3.3,3.3,.42,10),mat('#574538'));table.position.set(x,1.2,z);root.add(table);box(root,x,.3,z,1.3,1.5,1.3,mat('#59493b'));for(const side of [-1,1])box(root,x+side*4,.25,z,1,.9,1,mat('#675646'))}}
  for(const x of [-w*.42,w*.42]){box(root,x,.3,patioZ,2,3,2,mat('#b89a73'));const tree=new THREE.Mesh(new THREE.ConeGeometry(3.2,8,6),mats.leaf);tree.position.set(x,7,patioZ);root.add(tree)}for(const x of [-w*.37,w*.37]){const lamp=new THREE.PointLight('#ffc979',10,25);lamp.position.set(x,8,-d*.22);root.add(lamp)}group.add(root);return root}
 function fashionFlagship(group,b){const w=Math.max(180,b.w),d=Math.max(116,b.h),root=new THREE.Group();root.position.set(b.x+b.w/2,terrainY(b.x+b.w/2,b.y+b.h/2),b.y+b.h/2);flat(root,0,.04,0,w+36,d+32,mat('#b7aa91'));flat(root,0,.22,0,w+20,d+16,mat('#313538'));const black=mat('#161b20',.38,.32),brass=mat('#c69a48',.4,.5),glass=new THREE.MeshStandardMaterial({color:'#bbdfe2',roughness:.12,metalness:.12,transparent:true,opacity:.42}),inside=mat('#bd9b70',.7,.1);customMaterials.push(glass);box(root,0,.42,0,w,14,d,black);box(root,0,1.5,-d*.503,w*.88,11,.24,glass);for(let x=-w*.44;x<=w*.44;x+=w*.11)box(root,x,1.4,-d*.51,.5,11,.55,brass);box(root,0,14.9,0,w+5,1.1,d+5,black);box(root,0,15.6,0,w-16,.5,d-16,brass);box(root,0,14.25,-d*.53,w*.96,.36,.8,brass);
  const name=label('DEVOLT MOULD  ·  ABUJA','#12171c','#f3c46c',30);name.scale.set(w*.6,13,1);name.position.set(0,12.3,-d*.54);root.add(name);flat(root,0,.48,d*.33,w*.62,d*.25,inside);for(let row=0;row<2;row++)for(let col=0;col<5;col++){const x=(col-2)*w*.095,z=d*.25+row*d*.12;box(root,x,.5,z,2.5,4.5,1.4,brass);box(root,x,.7,z,4.7,.26,2.8,mat(['#a14138','#347b73','#d29b36','#293e64','#dfd1b5'][(col+row)%5]));box(root,x,.45,z+3,4,.6,1.2,inside)}for(let i=0;i<4;i++){const light=new THREE.PointLight('#ffcf88',13,36);light.position.set((i-1.5)*w*.23,11,-d*.22);root.add(light)}for(const x of [-w*.34,w*.34]){box(root,x,.34,-d*.55,1.5,5,1.5,mat('#c3ad87'));const planter=new THREE.Mesh(new THREE.CylinderGeometry(2,2.6,1.5,8),mat('#55534b'));planter.position.set(x,1.2,-d*.62);root.add(planter);const plant=new THREE.Mesh(new THREE.ConeGeometry(2.5,7,6),mats.leaf);plant.position.set(x,5.4,-d*.62);root.add(plant)}group.add(root);return root}
 function airportTerminal(group,b){const w=Math.max(620,b.w+120),d=Math.max(420,b.h+100),root=new THREE.Group();root.position.set(b.x+b.w/2,terrainY(b.x+b.w/2,b.y+b.h/2),b.y+b.h/2);flat(root,0,.04,0,w,d,mat('#555d61'));flat(root,0,.2,0,w-12,d-12,mat('#687276'));const terminalW=w*.67,terminalD=d*.3,glass=new THREE.MeshStandardMaterial({color:'#a7d4dc',roughness:.16,metalness:.08,transparent:true,opacity:.6,emissive:'#ffc979',emissiveIntensity:.24}),concrete=mat('#e1ded4',.66,.1),roof=mat('#53616a',.48,.4);customMaterials.push(glass);box(root,0,.45,-d*.22,terminalW,17,terminalD,concrete);box(root,0,2,-d*.22,terminalW-12,11,1,glass);for(let x=-terminalW*.46;x<terminalW*.5;x+=17)box(root,x,1.5,-d*.235,.6,12,1.2,mat('#435158',.38,.35));box(root,0,17.7,-d*.22,terminalW+16,1.1,terminalD+10,roof);const front=label('NNAMDI AZIKIWE  ·  INTERNATIONAL AIRPORT','#27333a','#f7e3aa',26);front.scale.set(112,15,1);front.position.set(0,15,-d*.39);root.add(front);
  box(root,terminalW*.42,.4,-d*.34,30,35,28,mat('#a99e8a'));box(root,terminalW*.42,34,-d*.34,34,2,32,mat('#525e64'));for(const y of [13,23,33]){box(root,terminalW*.42,y,-d*.34,31,.65,29,mat('#727c7e'))}const runway=mat('#333b40'),stripe=mat('#ece9dc');flat(root,0,.28,d*.16,w*.93,48,runway);for(let x=-w*.43;x<w*.44;x+=36)flat(root,x,.42,d*.16,18,1.1,stripe);for(const x of [-w*.39,w*.39])for(const z of [d*.16-22,d*.16+22]){const lamp=new THREE.PointLight('#ffcc79',7,35);lamp.position.set(x,3,z);root.add(lamp)}
  function plane(x,z,scale,paint){const p=new THREE.Group();p.position.set(x,.5,z);p.scale.setScalar(scale);const body=new THREE.Mesh(new THREE.CylinderGeometry(2.15,2.15,32,10),mat(paint,.36,.35));body.rotation.z=Math.PI/2;p.add(body);box(p,-1,0,0,13,.42,27,mat('#b5c1c5',.42,.48));box(p,-14,0,0,6,.3,9,mat('#cad0d0',.4,.48));box(p,-13,2.5,0,5,5,1.4,mat(paint,.35,.35));for(const xw of [-9,10])for(const zw of [-2.2,2.2]){const wheel=new THREE.Mesh(wheelGeometry,mats.dark);wheel.rotation.z=Math.PI/2;wheel.position.set(xw,-1.2,zw);p.add(wheel)}root.add(p)}plane(-w*.3,d*.16,.8,'#e7e6df');plane(w*.27,d*.16,.92,'#315f86');for(const x of [-w*.4,w*.4])for(const z of [-d*.4,d*.43]){const palm=new THREE.Mesh(new THREE.CylinderGeometry(.6,.9,8,6),mats.trunk);palm.position.set(x,4,z);root.add(palm);const crown=new THREE.Mesh(new THREE.ConeGeometry(3.2,7,6),mats.leaf);crown.position.set(x,10,z);root.add(crown)}group.add(root);return root}
 function nationalMosque(group,b){const w=b.w+72,d=b.h+72,root=new THREE.Group();root.position.set(b.x+b.w/2,terrainY(b.x+b.w/2,b.y+b.h/2),b.y+b.h/2);flat(root,0,.05,0,w,d,mat('#aeb99c'));flat(root,0,.22,0,w-22,d-22,mat('#d4c8ad'));const stone=mat('#e7decc',.7,.14),shadow=mat('#87949a',.48,.34),gold=mat('#d8ae58',.36,.5),glass=new THREE.MeshStandardMaterial({color:'#90b8c4',roughness:.2,metalness:.15,transparent:true,opacity:.62});customMaterials.push(glass);box(root,0,.35,0,w*.58,18,d*.43,stone);box(root,0,3,-d*.22,w*.5,11,.28,glass);for(let x=-w*.23;x<=w*.24;x+=w*.12)box(root,x,.4,-d*.225,.8,11,.8,shadow);box(root,0,18,0,w*.62,1.2,d*.47,shadow);const dome=new THREE.Mesh(new THREE.SphereGeometry(w*.15,20,12,0,Math.PI*2,0,Math.PI/2),gold);dome.position.set(0,19,0);root.add(dome);const finial=new THREE.Mesh(new THREE.ConeGeometry(2.5,9,8),gold);finial.position.set(0,19+w*.15+4.5,0);root.add(finial);for(const x of [-w*.28,w*.28])for(const z of [-d*.27,d*.27]){const shaft=new THREE.Mesh(new THREE.CylinderGeometry(2.4,3.4,48,8),stone);shaft.position.set(x,24,z);root.add(shaft);for(const y of [10,25,39]){const balcony=new THREE.Mesh(new THREE.CylinderGeometry(4.8,4.8,1.3,8),gold);balcony.position.set(x,y,z);root.add(balcony)}const spire=new THREE.Mesh(new THREE.ConeGeometry(2.5,11,8),gold);spire.position.set(x,53.5,z);root.add(spire)}const sign=label('ABUJA NATIONAL MOSQUE','#25323a','#f7e4b6',22);sign.scale.set(72,12,1);sign.position.set(0,25,-d*.49);root.add(sign);group.add(root);return root}
 function retailComplex(group,b){
  const w=Math.max(245,b.w+54),d=Math.max(176,b.h+48),root=new THREE.Group();root.position.set(b.x+b.w/2,terrainY(b.x+b.w/2,b.y+b.h/2),b.y+b.h/2);
  const lawn=mat('#8faf7d'),paving=mat('#bdb7a6'),stone=mat('#d5d1c6',.68,.08),dark=mat('#303a40',.45,.24),metal=mat('#59666a',.38,.48),glass=new THREE.MeshStandardMaterial({color:'#9acbd3',roughness:.19,metalness:.13,transparent:true,opacity:.64}),lit=new THREE.MeshStandardMaterial({color:'#f4dca5',roughness:.24,metalness:.04,emissive:'#dc923b',emissiveIntensity:.36});customMaterials.push(glass,lit);
  flat(root,0,.04,0,w+130,d+116,lawn);flat(root,0,.22,0,w+76,d+68,paving);flat(root,0,.3,d*.34,w+84,d*.23,mat('#505658'));flat(root,0,.38,-d*.26,w+52,d*.25,mat('#d8d2c1'));
  // Broad two-storey retail wings wrap a recessed, glazed central atrium.
  box(root,-w*.26,.42,-d*.08,w*.46,17,d*.62,stone);box(root,w*.26,.42,-d*.08,w*.46,17,d*.62,stone);box(root,0,.42,d*.1,w*.22,17,d*.36,stone);box(root,0,2.4,-d*.39,w*.46,12,.48,glass);box(root,0,2.4,-d*.394,w*.43,10,.2,lit);
  for(const wing of [-1,1])for(let level=0;level<2;level++){const y=.9+level*7.1;box(root,wing*w*.26,y,-d*.4,w*.42,5.8,.46,glass);for(let x=wing*w*.46;x<wing*w*.06;x+=-wing*19)box(root,x,.4,-d*.415,.8,16,.85,metal);box(root,wing*w*.26,y+6.15,-d*.4,w*.46,.48,.8,dark)}
  for(const x of [-w*.49,w*.49])for(const z of [-d*.36,d*.2])box(root,x,.45,z,2,17,2,metal);
  box(root,0,18,-d*.08,w+14,1.4,d+12,dark);box(root,0,18.9,-d*.08,w-26,.45,d-24,metal);box(root,0,12,-d*.5,w*.48,.72,10,dark);for(const x of [-w*.21,0,w*.21])box(root,x,.5,-d*.51,1.1,9,.9,metal);
  const fascia=label('JABI LAKE MALL  ·  SHOPPING  ·  DINING','#202a31','#f4e1b2',25);fascia.scale.set(92,13,1);fascia.position.set(0,15.3,-d*.51);root.add(fascia);
  // Outdoor parking, marked bays, short-stay drop-off and human-scale planting.
  for(let row=0;row<2;row++)for(let col=0;col<8;col++){const x=(col-3.5)*21,z=d*.34+(row-.5)*28;flat(root,x,.42,z,12,.28,mat('#ece8dc'));if((col+row)%3===0)carModel(root,x,z-4,['#d2d0c8','#293641','#b94b3f','#65716f'][((col+row)%4)],col%2?'sedan':'suv',false,true)}
  for(let i=0;i<7;i++){const x=(i-3)*34,z=d*.47;box(root,x,.38,z,1.2,7,1.2,mats.trunk);const crown=new THREE.Mesh(new THREE.SphereGeometry(5.4,8,6),i%2?mats.leaf:mats.leaf2);crown.position.set(x,10,z);crown.scale.set(1,1.08,1);root.add(crown);const bed=new THREE.Mesh(new THREE.CylinderGeometry(4.2,4.8,.55,8),mat('#546846'));bed.position.set(x,.64,z);root.add(bed)}
  for(const x of [-w*.4,-w*.2,w*.2,w*.4]){const lamp=new THREE.PointLight('#ffd99b',10,38);lamp.position.set(x,12,-d*.49);root.add(lamp)}
  const entrance=label('MAIN ENTRANCE  →','#303a40','#f3d38b',16);entrance.scale.set(40,6,1);entrance.position.set(0,4.5,-d*.55);root.add(entrance);group.add(root);return root;
 }
 function railwayStation(group,b){
  const w=Math.max(250,b.w+64),d=Math.max(170,b.h+54),root=new THREE.Group();root.position.set(b.x+b.w/2,terrainY(b.x+b.w/2,b.y+b.h/2),b.y+b.h/2);
  const concrete=mat('#d4d1c7',.7,.08),steel=mat('#45565e',.44,.46),glass=new THREE.MeshStandardMaterial({color:'#9acbd4',roughness:.17,metalness:.14,transparent:true,opacity:.65}),platform=mat('#c3baa6'),track=mat('#343c40',.94),rail=mat('#747b7b',.35,.75);customMaterials.push(glass);
  flat(root,0,.04,0,w+60,d+92,mat('#a4b38d'));flat(root,0,.2,0,w+34,d+70,concrete);box(root,0,.38,-d*.3,w*.78,13,d*.34,concrete);box(root,0,2,-d*.475,w*.7,9,.32,glass);for(let x=-w*.34;x<=w*.34;x+=w*.17)box(root,x,1.8,-d*.49,.55,9,.8,steel);box(root,0,13.8,-d*.3,w*.82,1.2,d*.38,steel);box(root,0,14.5,-d*.3,w*.68,.45,d*.29,mat('#82949b',.42,.42));
  const stationSign=label('IDU RAILWAY STATION','#27343b','#f4e4bf',24);stationSign.scale.set(86,12,1);stationSign.position.set(0,12,-d*.49);root.add(stationSign);
  for(let trackIndex=0;trackIndex<2;trackIndex++){const z=d*.14+trackIndex*43;flat(root,0,.24,z,w*.94,23,track);flat(root,0,.48,z-15,w*.88,8,platform);flat(root,0,.48,z+15,w*.88,8,platform);box(root,0,5.7,z-15,w*.78,.55,18,steel);box(root,0,5.7,z+15,w*.78,.55,18,steel);for(const x of [-w*.39,w*.39]){box(root,x,3,z-15,.8,5,.8,steel);box(root,x,3,z+15,.8,5,.8,steel)}
   for(const side of [-1,1]){box(root,0,.66,z+side*9,w*.9,.22,.55,rail);box(root,0,.66,z+side*21,w*.9,.22,.55,rail)}
   for(let x=-w*.41;x<w*.4;x+=18)flat(root,x,.38,z,8,.55,mat('#776b58'));
   // A two-car Abuja commuter train: shared simple forms, tinted windows and clear doors.
   for(let car=0;car<2;car++){const x=(car-.5)*w*.42;box(root,x,1.35,z,Math.min(86,w*.37),3.5,10,mat(car?'#e7e4da':'#d8dedc'));box(root,x,2.15,z-5.15,Math.min(77,w*.34),1.45,.18,glass);box(root,x,2.15,z+5.15,Math.min(77,w*.34),1.45,.18,glass);for(let win=-3;win<=3;win++)box(root,x+win*10,2.15,z-5.32,6,1.35,.1,mat('#6f9ca7',.26,.18));box(root,x,1.4,z-5.28,2.2,2.3,.12,mat('#617780'));for(const dx of [-w*.14,w*.14])for(const dz of [-4.2,4.2]){const wheel=new THREE.Mesh(wheelGeometry,mats.dark);wheel.rotation.z=Math.PI/2;wheel.position.set(x+dx,.42,z+dz);root.add(wheel)}}
  }
  for(const x of [-w*.44,w*.44]){const tree=new THREE.Mesh(new THREE.CylinderGeometry(1,1.3,8,7),mats.trunk);tree.position.set(x,4,-d*.42);root.add(tree);const crown=new THREE.Mesh(new THREE.SphereGeometry(5.5,8,6),mats.leaf);crown.position.set(x,10,-d*.42);root.add(crown)}
  for(const x of [-w*.32,0,w*.32]){const light=new THREE.PointLight('#ffe2ac',8,42);light.position.set(x,9,-d*.2);root.add(light)}group.add(root);return root;
 }
 function architecturalAsset(parent,b){const lod=new THREE.LOD();lod.addLevel(buildingModel(b,0),0);lod.addLevel(buildingModel(b,1),500);lod.addLevel(buildingModel(b,2),1350);lod.position.set(b.x+b.w/2,terrainY(b.x,b.y),b.y+b.h/2);lod.rotation.y=Number(b.rotation)||0;lod.scale.setScalar(Number(b.scale)||1);parent.add(lod);parent.userData.buildingLods.push(lod);return lod}
 diagnostic('procedural-world-build-start',{buildings:G.world.buildings?.length||0,chunkSize});
 G.world.assetBuilders=G.world.assetBuilders||Object.create(null);
 G.world.registerAssetBuilder=function(name,builder){if(typeof name!=='string'||!name||typeof builder!=='function')throw new TypeError('Asset builders need a name and a builder function.');G.world.assetBuilders[name]=builder;return builder};
 G.world.registerAssetBuilder('architecture',architecturalAsset);
 G.world.registerAssetBuilder('dealership',dealership);
 G.world.registerAssetBuilder('car-stand',carStand);
 G.world.registerAssetBuilder('restaurant-property',restaurantProperty);
 G.world.registerAssetBuilder('fashion-flagship',fashionFlagship);
 G.world.registerAssetBuilder('airport-terminal',airportTerminal);
 G.world.registerAssetBuilder('mosque',nationalMosque);
 G.world.registerAssetBuilder('construction-site',constructionSite);
 G.world.registerAssetBuilder('estate-gate',estateEntrance);
 G.world.registerAssetBuilder('park',parkAsset);
 G.world.registerAssetBuilder('landmark-rock-formation',rockFormation);
 for(const name of ['civic-bank','church'])G.world.registerAssetBuilder(name,architecturalAsset);
 G.world.registerAssetBuilder('retail-complex',retailComplex);
 G.world.registerAssetBuilder('transport-terminal',railwayStation);
 function terrainChunk(g,cx,cz){const side=9,step=chunkSize/side,vertices=[],indices=[];for(let j=0;j<=side;j++)for(let i=0;i<=side;i++){const x=cx+i*step,z=cz+j*step;vertices.push(x,terrainY(x,z),z)}for(let j=0;j<side;j++)for(let i=0;i<side;i++){const a=j*(side+1)+i,b=a+1,c=a+side+1,d=c+1;indices.push(a,c,b,b,c,d)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geo.setIndex(indices);geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,mats.grass);mesh.receiveShadow=true;g.add(mesh)}
 function makeChunk(cx,cz){const key=`${cx/chunkSize}:${cz/chunkSize}`,g=new THREE.Group();g.userData.key=key;g.userData.buildingLods=[];
  terrainChunk(g,cx,cz);
  // Abuja's planned districts use distinct green-space tones and keep future parcels legible.
  for(const district of G.world.districts||[]){const r=district.bounds;if(r.x>=cx+chunkSize||r.x+r.w<=cx||r.y>=cz+chunkSize||r.y+r.h<=cz)continue;if(district.style.includes('estate')||district.style.includes('residential')){const ix=Math.max(cx,r.x),iz=Math.max(cz,r.y),ax=Math.min(cx+chunkSize,r.x+r.w),az=Math.min(cz+chunkSize,r.y+r.h);rect(g,(ix+ax)/2,(iz+az)/2,ax-ix,az-iz,mat(district.style==='low-rise-estate'?'#a8c495':'#9dbb8e'))}}
  for(const p of G.world.futurePlots||[]){if(p.x>cx+chunkSize||p.x+p.w<cx||p.y>cz+chunkSize||p.y+p.h<cz)continue;rect(g,p.x+p.w/2,p.y+p.h/2,p.w,p.h,mats.soil);for(let x=p.x+20;x<p.x+p.w;x+=24){flat(g,x,terrainY(x,p.y)+.3,p.y,1,p.h,mat('#bd9c66'))}}
  drawRoads(g,cx,cz);
  if(cx<8900&&cx+chunkSize>7400&&cz<6530&&cz+chunkSize>6290){const left=Math.max(cx,7400),right=Math.min(cx+chunkSize,8900);rect(g,(left+right)/2,6405,right-left,84,mat('#424c53'));for(let x=left+15;x<right;x+=48)flat(g,x,terrainY(x,6405)+.2,6405,20,.45,mats.white)}
  for(const estate of G.world.residentialEstates||[]){if(estate.x>cx+chunkSize||estate.x+estate.w<cx||estate.y>cz+chunkSize||estate.y+estate.h<cz)continue;rect(g,estate.x+estate.w/2,estate.y+estate.h/2,estate.w,estate.h,mat('#a2bd92'));const roads=[estate.x+estate.w*.5,estate.x+estate.w*.25,estate.x+estate.w*.75];for(const x of roads)rect(g,x,estate.y+estate.h/2,7,estate.h,mat('#637077'));}
  for(const lake of G.world.lakes||[]){if(lake.x>cx+chunkSize||lake.x+lake.w<cx||lake.y>cz+chunkSize||lake.y+lake.h<cz)continue;const water=mat('#58a9c7',.22,.08),edge=mat('#cbbd9b',.9);rect(g,lake.x+lake.w/2,lake.y+lake.h/2,lake.w,lake.h,water);rect(g,lake.x+lake.w/2,lake.y-4,lake.w+8,8,edge);rect(g,lake.x+lake.w/2,lake.y+lake.h+4,lake.w+8,8,edge);rect(g,lake.x-4,lake.y+lake.h/2,8,lake.h+8,edge);rect(g,lake.x+lake.w+4,lake.y+lake.h/2,8,lake.h+8,edge)}
  const lotKey=`${cx/chunkSize}:${cz/chunkSize}`;buildCityFabric(g,G.world.cityLotsByChunk?.[lotKey],cx,cz);
  for(const r of G.world.roundabouts||[])if(Math.floor(r.x/chunkSize)===cx/chunkSize&&Math.floor(r.y/chunkSize)===cz/chunkSize)roundaboutAsset(g,r);
  for(const b of G.world.buildings||[]){const bounds=b.assetBounds||b;if(bounds.x>cx+chunkSize||bounds.x+bounds.w<cx||bounds.y>cz+chunkSize||bounds.y+bounds.h<cz)continue;const builderName=G.world.assetManifest?.[b.asset]?.builder,builder=G.world.assetBuilders?.[builderName]||G.world.assetBuilders?.[b.asset]||G.world.assetBuilders?.architecture;const centerX=bounds.x+bounds.w/2,centerY=bounds.y+bounds.h/2;if(Math.floor(centerX/chunkSize)!==cx/chunkSize||Math.floor(centerY/chunkSize)!==cz/chunkSize)continue;if(builder){builder(g,b,{THREE,mat,box,flat,rect,label,terrainY,buildingModel});continue}architecturalAsset(g,b)}
  const homes=(G.world.houseLots||[]).filter(home=>home.x<cx+chunkSize&&home.x+home.w>cx&&home.y<cz+chunkSize&&home.y+home.h>cz);addHomes(g,homes);
  treeBatch(g,cx,cz,(cx*31+cz*17)|0,Math.max(8,Math.floor(chunkSize/22)));
  scene.add(g);chunks.set(key,g);return g;
 }
 function discardChunk(key){const g=chunks.get(key);if(!g)return;scene.remove(g);g.traverse(o=>{if(o.geometry&&!sharedGeometry.has(o.geometry))o.geometry.dispose();if(o.isSprite&&o.material)o.material.dispose()});chunks.delete(key)}
 function refreshLocation(location,previous){for(const item of [previous,location]){if(!item)continue;const bounds=item.assetBounds||item,x0=Math.max(0,Math.floor(bounds.x/chunkSize)*chunkSize),y0=Math.max(0,Math.floor(bounds.y/chunkSize)*chunkSize),x1=Math.min(G.W,Math.floor((bounds.x+(bounds.w||1))/chunkSize)*chunkSize),y1=Math.min(G.H,Math.floor((bounds.y+(bounds.h||1))/chunkSize)*chunkSize);for(let x=x0;x<=x1;x+=chunkSize)for(let y=y0;y<=y1;y+=chunkSize)discardChunk(String(x/chunkSize)+':'+String(y/chunkSize))}}
 const people=new Map(),vehicles=new Map(),playerFigure=person();scene.add(playerFigure);
 function person(){const g=new THREE.Group();const skin=mat('#70462f'),shirt=mat('#198a67'),pants=mat('#17243a');const torso=new THREE.Mesh(personBodyGeometry,shirt);torso.position.y=1.05;g.add(torso);const head=new THREE.Mesh(personHeadGeometry,skin);head.position.y=1.8;g.add(head);box(g,-.22,.04,0,.28,.12,.32,pants);box(g,.22,.04,0,.28,.12,.32,pants);return g}
 function syncActors(){const actors=G.world.npcs||[],activeIds=new Set(actors.map(n=>n.id));for(const n of actors){let o=people.get(n.id);if(!o){o=person();scene.add(o);people.set(n.id,o)}o.position.set(n.x,terrainY(n.x,n.y),n.y);o.visible=true}
  for(const [id,o]of people)if(!activeIds.has(id)){scene.remove(o);people.delete(id)}
  for(const c of G.world.cars||[]){if(!c.id&&!c.owned&&!c.taxi&&!c.bus)continue;const id=c.id||c.name||'player-car';let o=vehicles.get(id);if(!o){o=carModel(scene,c.x,c.y,c.color,c.kind);vehicles.set(id,o)}o.position.set(c.x,terrainY(c.x,c.y),c.y)}
 }
 let visible=true,lastSync=0,firstRendered=false;
 function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.left=-innerWidth/2;camera.right=innerWidth/2;camera.top=innerHeight/2;camera.bottom=-innerHeight/2;camera.updateProjectionMatrix()}
 addEventListener('resize',resize);resize();
 function render(){if(!visible)return;const s=G.state;if(!s)return;updateLighting();const scale=(G.view.scale||1)*1.047;
  const panX=G.view.panX||0,panY=G.view.panY||0;
  const targetX=clamp(s.x-(panX/.74+panY/.38)/(2*(G.view.scale||1)),0,G.W),targetZ=clamp(s.y-(panY/.38-panX/.74)/(2*(G.view.scale||1)),0,G.H);
  const viewHeight=innerHeight/scale;camera.left=-innerWidth/(2*scale);camera.right=innerWidth/(2*scale);camera.top=viewHeight/2;camera.bottom=-viewHeight/2;
  const elev=Math.asin(.61),horizontal=Math.max(viewHeight,innerWidth/scale)*1.34;
  camera.position.set(targetX+Math.cos(Math.PI/4)*horizontal,terrainY(targetX,targetZ)+Math.tan(elev)*horizontal,targetZ+Math.sin(Math.PI/4)*horizontal);
  camera.lookAt(targetX,terrainY(targetX,targetZ),targetZ);camera.updateProjectionMatrix();camera.updateMatrixWorld();
  const r=Math.max(chunkSize*1.75,(innerWidth/(1.48*scale)+innerHeight/(.76*scale))/2+chunkSize*.5),minX=Math.max(0,Math.floor((targetX-r)/chunkSize)*chunkSize),maxX=Math.min(G.W,Math.ceil((targetX+r)/chunkSize)*chunkSize),minZ=Math.max(0,Math.floor((targetZ-r)/chunkSize)*chunkSize),maxZ=Math.min(G.H,Math.ceil((targetZ+r)/chunkSize)*chunkSize),needed=new Set();
  for(let x=minX;x<maxX;x+=chunkSize)for(let z=minZ;z<maxZ;z+=chunkSize)needed.add(String(x/chunkSize)+':'+String(z/chunkSize));
  const queued=[...needed].filter(k=>!chunks.has(k)).sort((a,b)=>{const[ax,az]=a.split(':').map(Number),[bx,bz]=b.split(':').map(Number);return Math.hypot((ax+.5)*chunkSize-targetX,(az+.5)*chunkSize-targetZ)-Math.hypot((bx+.5)*chunkSize-targetX,(bz+.5)*chunkSize-targetZ)});
  for(const key of queued.slice(0,3)){const[x,z]=key.split(':').map(Number);makeChunk(x*chunkSize,z*chunkSize)}
  for(const key of chunks.keys())if(!needed.has(key))discardChunk(key);
  for(const g of chunks.values()){for(const lod of g.userData.buildingLods||[])lod.update(camera);const homes=g.userData.homeLOD;if(!homes)continue;let changed=false;for(const item of homes.items){const near=Math.hypot(item.x-targetX,item.z-targetZ)<260;if(near===item.near)continue;item.near=near;if(near){const detail=makeHouse(item.h);detail.position.set(item.x,item.ground,item.z);item.parent.add(detail);item.detail=detail}else if(item.detail){item.parent.remove(item.detail);item.detail.traverse(o=>{if(o.geometry&&!sharedGeometry.has(o.geometry))o.geometry.dispose()});item.detail=null}dummyHome(item,homes.bodies,homes.roofs);changed=true}if(changed){homes.bodies.instanceMatrix.needsUpdate=true;homes.roofs.instanceMatrix.needsUpdate=true}}
  if(performance.now()-lastSync>400){syncActors();lastSync=performance.now()}
  const player=s.vehicle?vehicles.get(s.vehicle.id||s.vehicle.name):null;
  if(player){player.position.set(s.x,terrainY(s.x,s.y),s.y);player.rotation.y=-(s.angle||0);player.visible=true;playerFigure.visible=false}else{playerFigure.position.set(s.x,terrainY(s.x,s.y),s.y);playerFigure.rotation.y=-(s.angle||0);playerFigure.visible=true}
  renderer.render(scene,camera);if(!firstRendered){firstRendered=true;diagnostic('first-render-complete',{drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,chunks:chunks.size})}
 }
 const api={ready:true,renderer,scene,camera,chunks,get stats(){return{chunks:chunks.size,buildings:G.world.buildings.length,cityLots:G.world.cityLots?.length||0,houseLots:G.world.houseLots.length,roads:G.world.roadSegments?.length||0,roundabouts:G.world.roundabouts?.length||0,trees:[...chunks.values()].reduce((n,c)=>n+(c.userData.treeCount||0),0),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles}},render,refreshLocation,setVisible(v){visible=!!v;canvas.style.display=v?'block':'none'},dispose(){removeEventListener('resize',resize);for(const key of chunks.keys())discardChunk(key);renderer.dispose();materialCache.forEach(m=>m.dispose());customMaterials.forEach(m=>m.dispose());labelCache.forEach(t=>t.dispose());textures.forEach(t=>t.dispose());canvas.remove()}};
 G.world.threeWorld=api;
 diagnostic('three-world-initialization-complete',{canvasConnected:canvas.isConnected,rendererRevision:THREE.REVISION});
 return api;
}

