(function(){const G=window.Game;G.openPanel=function(panel,tab){G.ui.panel=panel;G.ui.panelTab=tab||'';document.getElementById('shade').classList.remove('hidden');G.renderPanel(panel,tab)};G.closePanel=function(){G.ui.panel='';document.getElementById('shade').classList.add('hidden')};G.renderPanel=function(panel,tab){panel=panel||G.ui.panel;tab=tab||G.ui.panelTab;G.ui.panelTab=tab;let title='Phone',sub='Your everyday tools on the move.',body='';if(panel==='phone'){title='Your phone';sub='';body=phoneContents(tab||'apps')}else if(panel==='inventory'){title='Your bag';sub='Things you are carrying.';body=inventoryContents()}
else if(panel==='map'){title='City map';sub='Choose a place to travel to. Walking and driving are both options.';body=`<div class="map-legend">${G.world.buildings.map(b=>`<button onclick="Game.travel('${b.id}')">${b.icon} ${b.name}<span>${b.type}</span></button>`).join('')}</div>`}
else if(panel==='mission'){let m=G.missionsList[G.state.missions];title='Your story';sub=`Chapter ${Math.min(G.state.missions+1,10)} of 10`;body=m?`<div class="dialog"><b>${m[0]}</b><br>${m[1]}<div class="progress" style="margin-top:12px"><span style="width:${Math.min(100,(G.state.goalProgress/m[3])*100)}%"></span></div><small>${Math.min(G.state.goalProgress,m[3])} / ${m[3]} progress · reward ${G.money(m[4])}</small></div><h3>Finished chapters</h3>${G.state.completed.map(x=>`<div class="kv"><span>✓ ${x}</span><small>Complete</small></div>`).join('')}`:'<div class="dialog">You completed the opening story. More chapters arrive as the game grows.</div>'}
else if(panel==='building'){let b=G.world.buildings.find(x=>x.id===tab);title=b?b.icon+' '+b.name:'City location';sub=b?b.desc:'';body=b?buildingContents(b):''}
else if(panel==='person'){let n=G.world.npcs.find(x=>x.id===tab);title=n?n.emoji+' '+n.name:'Neighbor';sub=n?n.job+' · '+(n.mood===0?'In a good mood':'Out and about'):'';body=n?`<div class="dialog">${n.name} is ${n.mood===0?'having a relaxed morning':'on the move'} around the district. A friendly hello can grow into a real connection.</div><div class="itemlist"><div class="itemrow"><div class="item-icon">💬</div><div><strong>Have a conversation</strong><small>Build rapport and lift your mood.</small></div><button class="action" onclick="Game.action('talk','${n.id}')">Talk</button></div><div class="itemrow"><div class="item-icon">🤝</div><div><strong>Ask to be friends</strong><small>Requires a little trust first.</small></div><button class="action soft" onclick="Game.action('friend','${n.id}')">Ask</button></div>${G.state.relationships[n.id]>=2?`<div class="itemrow"><div class="item-icon">☕</div><div><strong>Invite to lunch</strong><small>Spend ₦1,500 together.</small></div><button class="action soft" onclick="Game.action('date','${n.id}')">Invite</button></div>`:''}</div>`:''}
else if(panel==='save'){title='Save & settings';sub='Your progress is saved in this browser on this device.';body=`<div class="itemlist"><div class="itemrow"><div class="item-icon">💾</div><div><strong>Save game</strong><small>Save your current position, money, mission, and stats.</small></div><button class="action" onclick="Game.save()">Save</button></div><div class="itemrow"><div class="item-icon">↩</div><div><strong>Load saved game</strong><small>Restore the most recent local save.</small></div><button class="action soft" onclick="Game.action('load')">Load</button></div><div class="itemrow"><div class="item-icon">🔊</div><div><strong>Sound effects</strong><small>Soundscape is not yet implemented.</small></div><button class="action soft" onclick="Game.toast('Audio is planned for a later update.')">Options</button></div><div class="itemrow"><div class="item-icon">＋</div><div><strong>New life</strong><small>Start over. This replaces your current save.</small></div><button class="action danger" onclick="Game.action('newlife')">Reset</button></div></div>`}
let html=`<h2>${title}</h2><p class="panel-sub">${sub}</p>${body}`;document.getElementById('panel-window').classList.toggle('phone-mode',panel==='phone');document.getElementById('panel-content').innerHTML=html;};
const phoneApps=[['Jobs','💼','#89c91e'],['Messages','💬','#3187ed'],['Contacts','📞','#24b679'],['Meet people','🛡️','#11151e'],['Salary','📈','#101519'],['Tickets','🎟️','#9b52e9'],['Games','🎮','#171723'],['Nollywood','🎬','#12151b'],['Sports','⚽','#ec3240'],['Chowdeck','🛵','#f2385a'],['Bank','🏦','#7546e9'],['Boutique','👠','#c94da9'],['Forbes','👑','#143e31'],['Houses','🔑','#dc8c49'],['Cars','🚘','#2c84e7'],['Invite','🔗','#f5a31d'],['Health','💊','#eb5372'],['Invest','💼','#84c928'],['Business','🏪','#1b7659'],['Family','💞','#de52a3'],['City Gov','🏛️','#1b9364'],['Police','🚓','#244a9b'],['My Ads','📣','#cd3989'],['Settings','⚙️','#97a5b6']].map((a,i)=>({id:['jobs','messages','contacts','people','salary','events','games','nollywood','sports','food','bank','boutique','finance','houses','vehicles','invite','health','invest','business','family','government','police','ads','settings'][i],name:a[0],icon:a[1],color:a[2]}));
G.launchApp=function(id){G.renderPanel('phone',id)};G.openChat=function(id){G.renderPanel('phone','chat-'+id)};
function phoneContents(tab){let s=G.state,app=phoneApps.find(a=>a.id===tab)||phoneApps.find(a=>tab.startsWith(a.id+'-'))||{id:'messages',name:'Messages',icon:'\u{1F4AC}'};if(tab==='apps'){let tm=G.timeInfo();return `<div class="phone-device"><div class="phone-screen launcher"><div class="dynamic-island"></div><div class="ios-status"><span id="phone-status-time">${tm.phoneTime}</span><span>●●● &nbsp; 4G &nbsp; ▰</span></div><button class="phone-close" onclick="Game.closePanel()">×</button><div class="phone-lock-time" id="phone-home-time">${tm.phoneTime}</div><div class="phone-lock-date" id="phone-home-date">${tm.dateLine}</div><div class="phone-app-grid">${phoneApps.map(a=>`<button class="phone-app" onclick="Game.launchApp('${a.id}')"><span class="app-icon" style="--app:${a.color}">${a.icon}</span><span>${a.name}</span></button>`).join('')}</div><div class="phone-dock"><button onclick="Game.launchApp('contacts')">📱</button><button onclick="Game.launchApp('messages')">💬</button><button onclick="Game.closePanel();Game.openPanel('map')">🗺️</button><button onclick="Game.launchApp('settings')">⚙️</button></div><div class="phone-home-indicator"></div></div></div>`}
let content='',title=app.name;const back=`<div class="phone-app-top"><button onclick="Game.renderPanel('phone','apps')">‹</button><b>${app.icon} ${title}</b><button onclick="Game.closePanel()">×</button></div>`;
if(tab==='jobs')content=`<div class="phone-card"><b>Find your next shift</b><p>Work hard, build skills, and grow your salary.</p></div>${phoneJobs()}`;
else if(tab==='bank')content=phoneBank();else if(tab==='contacts'||tab==='people'||tab==='messages'||tab==='messages-updates'||tab==='family'||tab.startsWith('chat-'))content=phoneContacts(tab);
else if(tab==='salary')content=`<div class="phone-card"><small>CAREER PROFILE</small><h3>${s.job||'No job yet'}</h3><p>Level ${s.jobLevel+1} · Driving ${s.driving} · Intelligence ${s.intelligence}</p><strong>${s.job?'₦2,400 average per shift':'Apply to your first role'}</strong></div>${phoneJobs()}`;
else if(tab==='events')content=`<div class="phone-card"><small>WHAT'S ON</small><h3>Abuja this week</h3><p>Community, music, food, and the people who make the city.</p></div>${[['🎤','Open mic night','Sunset Lounge · 7 PM · ₦800'],['🌳','Millennium Park walk','Saturday · Free'],['🍛','Wuse food fair','Wuse Market · ₦500']].map((x,i)=>`<div class="phone-listrow"><span>${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div><button onclick="Game.action('event','${i}')">Join</button></div>`).join('')}`;
else if(tab==='games')content=`<div class="phone-card"><small>YOUR STORY · CHAPTER ${Math.min(s.missions+1,10)}</small><h3>${G.missionsList[s.missions]?.[0]||'A life of your own'}</h3><p>${G.missionsList[s.missions]?.[1]||'Keep growing your life.'}</p><div class="progress"><span style="width:${G.missionsList[s.missions]?Math.min(100,s.goalProgress/G.missionsList[s.missions][3]*100):100}%"></span></div></div><button class="phone-wide" onclick="Game.openPanel('mission')">View story progress</button>`;
else if(tab==='nollywood')content=`<div class="phone-card movie-card"><small>NAIJA SCREEN</small><h3>Stories from home</h3><p>Pick a film, get comfortable, and enjoy a little downtime.</p></div>${[['The Last Bus to Wuse','🎞️'],['Market Day','🎬'],['Under the Harmattan Sky','🍿']].map(x=>`<div class="phone-listrow"><span>${x[1]}</span><div><b>${x[0]}</b><small>Comedy · 1h 42m · ₦500</small></div><button onclick="Game.action('movie','${x[0]}')">Watch</button></div>`).join('')}`;
else if(tab==='sports')content=`<div class="phone-card"><small>CAPITAL SPORTS</small><h3>Match centre</h3><p>Local fixtures and friendly predictions. No real-money betting.</p></div><div class="phone-listrow"><span>⚽</span><div><b>Abuja City FC　vs　Plateau United</b><small>Tonight · Friendly · 0 – 0</small></div><button onclick="Game.action('sports')">Follow</button></div><div class="phone-listrow"><span>🏀</span><div><b>Pick the match result</b><small>Correct picks earn reputation, not cash.</small></div><button onclick="Game.action('sports')">Pick</button></div>`;
else if(tab==='food')content=`<div class="phone-card"><small>CHOWDECK · LOCAL DELIVERY</small><h3>Good food is close by</h3><p>Order a meal to your current neighborhood.</p></div><div class="phone-listrow"><span>🍛</span><div><b>Jollof rice & chicken</b><small>₦1,200 · Hunger +38</small></div><button onclick="Game.action('delivery')">Order</button></div><div class="phone-listrow"><span>🥤</span><div><b>Cold water</b><small>₦100 · Energy +4</small></div><button onclick="Game.action('water')">Order</button></div>`;
else if(tab==='boutique')content=`<div class="phone-card"><small>FRESH FITS</small><h3>Change your look</h3><p>Choose an outfit for the day.</p></div>${[['green','Everyday green','🟢',0],['coral','Coral streetwear','🧡',1800],['blue','Blue kaftan','🔵',3200]].map(x=>`<div class="phone-listrow"><span>${x[2]}</span><div><b>${x[1]} ${s.outfit===x[0]?'· WORN':''}</b><small>${x[3]?G.money(x[3]):'Free'}</small></div><button onclick="Game.action('outfit','${x[0]}')">${s.outfit===x[0]?'On':'Choose'}</button></div>`).join('')}`;
else if(tab==='finance')content=`<div class="phone-card"><small>YOUR MONEY</small><h3>Personal balance sheet</h3><p>Cash ${G.money(s.cash)} · Bank ${G.money(s.bank)}</p><strong>Estimated net worth ${G.money(s.cash+s.bank+(s.business?.profit||0))}</strong></div><button class="phone-wide" onclick="Game.renderPanel('phone','bank')">Open Naija Bank</button>${s.business?`<button class="phone-wide" onclick="Game.renderPanel('phone','business')">Manage ${s.business.name}</button>`:''}`;
else if(tab==='houses')content=phoneHouses();
else if(tab==='business')content=businessContents();
else if(tab==='vehicles')content=`<div class="phone-card"><small>GARAGE</small><h3>${s.vehicle?'Driving '+s.vehicle.name:'On foot'}</h3><p>Fuel ${Math.round(s.fuel)}% · Vehicle condition ${100-Math.round(s.carDamage)}%</p></div>${phoneVehicles()}`;
else if(tab==='invite')content=`<div class="phone-card"><small>BRING YOUR PEOPLE</small><h3>Invite a friend along</h3><p>Make a connection in the city. Invites are local game actions.</p></div>${G.world.npcs.slice(0,6).map(n=>`<div class="phone-listrow"><span>${n.emoji}</span><div><b>${n.name}</b><small>Friendship ${s.relationships[n.id]||0}/3</small></div><button onclick="Game.action('invite','${n.id}')">Invite</button></div>`).join('')}`;
else if(tab==='health')content=`<div class="phone-card"><small>WELLNESS</small><h3>${Math.round(s.health)}% health</h3><p>Hunger ${Math.round(s.hunger)}% · Energy ${Math.round(s.energy)}% · Happiness ${Math.round(s.happiness)}%</p></div><button class="phone-wide" onclick="Game.travel('b2')">Find a clinic</button><button class="phone-wide" onclick="Game.action('heal')">Get care · ₦2,000</button>`;
else if(tab==='invest')content=`<div class="phone-card"><small>NAIJA INVEST</small><h3>Build a steady future</h3><p>Buy a low-risk city savings certificate. It pays 5% after each real calendar day.</p><strong>Invested ${G.money(s.investments||0)}</strong></div><button class="phone-wide" onclick="Game.action('invest')">Buy certificate · ₦5,000</button>`;
else if(tab.startsWith('government'))content=phoneGovernment(tab);
else if(tab==='police')content=`<div class="phone-card"><small>COMMUNITY SAFETY</small><h3>Wanted level ${s.wanted}/3</h3><p>${s.wanted?'Outstanding fine '+G.money(s.wanted*1200):'No open police cases. Keep the city safe.'}</p></div>${s.wanted?`<button class="phone-wide" onclick="Game.action('police')">Pay fine · ${G.money(s.wanted*1200)}</button>`:''}<button class="phone-wide" onclick="Game.travel('b3')">Visit Central Police Post</button>`;
else if(tab==='ads')content=`<div class="phone-card"><small>MY ADS</small><h3>Share your shop with the city</h3><p>Post a small neighborhood notice. Your ad is only visible in this local game.</p></div><button class="phone-wide" onclick="Game.action('ad')">Post a notice · ₦1,000</button>${s.ad?`<div class="phone-listrow"><span>📣</span><div><b>${s.ad}</b><small>Your active city notice</small></div></div>`:''}`;
else if(tab==='settings')content=`<div class="phone-card"><small>PHONE SETTINGS</small><h3>NaijaPhone</h3><p>Local Nigeria time · Africa/Lagos. Save data stays in this browser on this device.</p></div><button class="phone-wide" onclick="Gamfid]?.at(-1);return `<button class="phone-listrow chat-row" onclick="Game.openChat('${n.id}')"><span>${n.emoji||'👤'}</span><div><b>${handle(n)}</b><small>${latest?'You: '+latest.text:['You: Hello','You: Oyanw','You: 👋','See you around!'][i%4]}</small></div><small>${i?'19m':'13m'}</small></button>`}).join('')}</div>`;
  if(tab.startsWith('chat-')){
    const id=tab.slice(5),n=people.find(x=>x.id===id)||G.world.npcs.find(x=>x.id===id);if(!n)return '<div class="phone-card">This chat is no longer available.</div>';
    let msgs=s.phoneMessages?.[id]||[{from:'them',text:'Hii',time:'1:15'}];
    return `<div class="chat-profile"><span>${n.emoji||'👤'}</span><b>${handle(n)}</b><small>🔒 Private · only you and ${handle(n)} can see this</small><div class="chat-actions"><button onclick="Game.action('invite','${id}')">🏠 Invite over</button><button onclick="Game.openPanel('person','${id}')">Visit them</button><button onclick="Game.action('transfer')">💸 Send money</button><button onclick="Game.action('delivery')">🍲 Buy food</button><button onclick="Game.toast('Contact blocked.')">🚫 Block</button><button onclick="Game.toast('Report noted for this local save.')">⚑ Report</button></div></div><div class="chat-day">Today</div><div class="chat-messages">${msgs.map(m=>`<div class="phone-bubble ${m.from==='you'?'outgoing':'incoming'}">${m.text}<small>${m.time||'Now'}${m.from==='you'?' · Sent':''}</small></div>`).join('')}</div><div class="chat-suggestions"><button onclick="document.getElementById('phone-message-input').value='How far? 👋🏾'">How far? 👋🏾</button><button onclick="document.getElementById('phone-message-input').value='I dey o 😁'">I dey o 😁</button><button onclick="document.getElementById('phone-message-input').value='Wetin dey happen?'">Wetin dey happen?</button></div><div class="chat-compose"><input id="phone-message-input" placeholder="Message ${handle(n)}..." onkeydown="if(event.key==='Enter')Game.action('sendmessage','${id}')"/><button onclick="Game.action('sendmessage','${id}')">➤</button></div>`;
  }
  const fixed=[['Mummy','👵🏾','Always picks up'],['Femi','🧑🏿','Acquaintance'],['Aisha','👩🏽','Stranger']];
  return `<div class="phone-list">${fixed.map(c=>`<div class="phone-listrow"><span>${c[1]}</span><div><b>${c[0]}</b><small>${c[2]}</small></div><button onclick="Game.action('call','${c[0]}')">☎</button></div>`).join('')}</div><h4>FIND A PLAYER</h4><div class="phone-search"><input placeholder="Search by username" oninput="document.querySelectorAll('.contact-row').forEach(r=>r.hidden=!r.innerText.toLowerCase().includes(this.value.toLowerCase()))" /></div><h4>PLAYERS YOU'VE MET</h4><div class="phone-list">${people.map(n=>`<button class="phone-listrow contact-row" onclick="Game.openPanel('person','${n.id}')"><span>${n.emoji||'👤'}</span><div><b>${handle(n)}</b><small>${(s.relationships[n.id]||0)>1?'Padi':'Acquaintance'}</small></div><span class="contact-chat" onclick="event.stopPropagation();Game.openChat('${n.id}')">•••</span></button>`).join('')}</div>`;
};

function phoneGovernment(tab){
 const roles=['Governor','Senator','President'];
 const key=roles.find(r=>tab.toLowerCase().endsWith(r.toLowerCase()))||'Governor';
 const data={Governor:['@Frankie','Good Abuja ahead','🏛️',9543],Senator:['@Fran6ix','Give away every week','⚖️',808],President:['@Frankie','Free funds for everyone','🇳🇬',948]}[key];
 const already=G.state.electionVotes&&G.state.electionVotes[key];
 const candidates=[data,['@Udindu','The People’s Voice','👨🏾',1512],['@Tohbiszn','Money every evening for my voters','👨🏿',447],['@Goodiell','Vote and I’ll message you after','👨🏽',437]];
 return `<div class="phone-segment">${roles.map(r=>`<button class="${r===key?'selected':''}" onclick="Game.renderPanel('phone','government-${r.toLowerCase()}')">${r}</button>`).join('')}</div><div class="phone-card election-lead"><small>${key.toUpperCase()} OF NIGERIA · THIS WEEK</small><h3>${data[0]}</h3><p>“${data[1]}” · ${data[3]} votes</p><small>Term ends Sunday at 8 PM</small></div><div class="phone-card polling-unit"><b>🗳️ Vote at the Abuja Polling Unit</b><p>One ballot paper per race · polls close in 6d 17h</p></div><div class="phone-search"><input placeholder="Search candidates by @username" oninput="document.querySelectorAll('.candidate-row').forEach(r=>r.hidden=!r.innerText.toLowerCase().includes(this.value.toLowerCase()))" /></div>${candidates.map((c,i)=>`<article class="phone-candidate candidate-row"><span>${c[2]}</span><div><b>${c[0]}</b><small>“${c[1]}”</small></div><small>${c[3]} votes</small><button onclick="Game.action('vote','${key}|${c[0]}')">${already===c[0]?'✓ Voted':'Vote'}</button></article>`).join('')}`;
}
function phoneHouses(){
 const s=G.state;
 const homes=[['Face-me-I-face-you','Mushin','6×6',2400,7200],['Self-contain','Yaba','7×7',6000,18000],['Mini-flat','Lekki Phase 1','10×10',17000,51000],['Duplex','Ikoyi','12×12',250000,750000],['Mansion','Banana Island','14×14',1500000,4500000],['Hall of Residence','UNILAG, Akoka','6×6',1200,3600]];
 return `<p class="house-intro">Found a better place? Pay the landlord and agent and your furniture moves with you.</p>${homes.map(h=>`<article class="phone-house"><div><b>${h[0]} · ${h[1]}</b><small>${h[2]}</small></div><div><small>₦${h[3].toLocaleString()}/week</small><button onclick="Game.action('movehome','${h[0]}|${h[1]}|${h[3]}|${h[4]}')">Move in ₦${h[4].toLocaleString()}</button></div></article>`).join('')}`;
}

phoneBank=function(){
 const s=G.state,history=s.bankHistory||[];
 const earned=(s.shiftsCompleted||0)*(s.job==='Junior web designer'?9900:s.job==='Banker'?11600:s.job==='Musician'?7400:s.job==='Cafe assistant'?2000:2400);
 return `<div class="phone-card bank-balance"><small>NAIJA BANK · CURRENT ACCOUNT</small><small>Balance</small><h3>${G.money(s.bank+s.cash)}</h3><p>Cash in wallet ${G.money(s.cash)} · Bank ${G.money(s.bank)}</p></div><button class="phone-wide" onclick="Game.toast('Your in-game wallet is ready.')">💳 Top up wallet</button><div class="bank-row"><span>Earned today</span><b>${G.money(earned)}</b></div><div class="phone-card tax-card"><b>🧾 Income tax this week <small>0% now</small></b><p>Tax is calculated on your earned wages. Your game money stays in the simulator.</p><div>Earned ${G.money(earned)} <span>Tax paid ₦0</span></div></div><div class="bank-row"><span>Weekly rent</span><b>${G.money(s.rent)}</b></div><div class="bank-row"><span>Rent due</span><b>In 6 days</b></div><h4>🧾 LAST RECEIPT</h4><div class="phone-card receipt-card"><b>🏠 ${s.home}</b><small>${G.timeInfo().dateLine} · paid from wallet</small><hr/><div>Weekly rent <b>${G.money(s.rent)}</b></div><small>Your most recent housing receipt</small></div><h4>MONEY HISTORY</h4>${history.length?history.slice(0,8).map(x=>`<div class="phone-listrow"><span>${x.amount<0?'↗':'↙'}</span><div><b>${x.label}</b><small>${x.when}</small></div><strong>${x.amount<0?'−':''}${G.money(Math.abs(x.amount))}</strong></div>`).join(''):'<p class="house-intro">No bank activity yet. Deposit or withdraw from your account.</p>'}<div class="phone-form"><input id="bank-amount" type="number" min="1" placeholder="Amount in naira"><button onclick="Game.action('deposit')">Deposit</button><button class="light" onclick="Game.action('withdraw')">Withdraw</button></div><div class="phone-listrow"><span>↗</span><div><b>Transfer to a neighbor</b><small>₦500 to a local contact</small></div><button onclick="Game.action('transfer')">Send</button></div>`;
};


G.openBuilding=function(b){G.openPanel('building',b.id)};G.openPerson=function(n){G.openPanel('person',n.id)};G.openPersonById=function(id){G.openPanel('person',id)};
G.action=function(act,arg){let s=G.state,n,b,amount,el;switch(act){case'talk':n=G.world.npcs.find(x=>x.id===arg);if(!n)break;s.happiness=Math.min(100,s.happiness+8);n.friend++;s.relationships[n.id]=Math.min(3,(s.relationships[n.id]||0)+1);s.reputation++;G.missionEvent('talk');G.toast('You had a nice chat with '+n.name+'.');G.renderPanel('person',n.id);G.saveSilent();break;
case'vote':{const v=String(arg).split('|'),role=v[0],candidate=v[1];s.electionVotes=s.electionVotes||{};if(s.electionVotes[role]){G.toast('You already voted in this race.');break}s.electionVotes[role]=candidate;s.reputation++;G.toast('Your vote for '+candidate+' was counted.');G.renderPanel('phone','government-'+role.toLowerCase());G.saveSilent();break}case'movehome':{const h=String(arg).split('|'),cost=Number(h[3]),weekly=Number(h[2]);if(s.cash<cost){G.toast('You need '+G.money(cost)+' to move in.');break}s.cash-=cost;s.home=h[0]+' ? '+h[1];s.rent=weekly;G.toast('You moved into '+s.home+'.');G.renderPanel('phone','houses');G.saveSilent();break}case'sendmessage':n=G.world.npcs.find(x=>x.id===arg);el=document.getElementById('phone-message-input');amount=el&&el.value.trim();if(!n||!amount){G.toast('Write a message first.');break}s.phoneMessages=s.phoneMessages||{};s.phoneMessages[n.id]=s.phoneMessages[n.id]||[];s.phoneMessages[n.id].push({from:'you',text:amount,time:G.timeInfo().phoneTime});s.phoneMessages[n.id].push({from:'them',text:['I hear you ??','Oyanw!','We go talk soon.','No wahala ????'][s.phoneMessages[n.id].length%4],time:G.timeInfo().phoneTime});G.renderPanel('phone','chat-'+n.id);G.saveSilent();break;case'call':s.happiness=Math.min(100,s.happiness+3);G.toast('You had a quick call with '+arg+'.');G.renderPanel('phone','contacts');G.saveSilent();break;case'quitjob':s.job=null;s.jobLevel=0;G.toast('You left your job. You can apply for another one any time.');G.renderPanel('phone','jobs');G.saveSilent();break;case'friend':n=G.world.npcs.find(x=>x.id===arg);if(!n)break;if((s.relationships[n.id]||0)<1){G.toast('Talk to them first to build some trust.');break}s.relationships[n.id]=Math.max(2,s.relationships[n.id]);G.missionEvent('friend');G.toast(n.name+' is happy to be friends.');G.renderPanel('person',n.id);G.saveSilent();break;
case'date':n=G.world.npcs.find(x=>x.id===arg);if(s.cash<1500){G.toast('You need ₦1,500 for lunch.');break}s.cash-=1500;s.happiness=Math.min(100,s.happiness+15);s.relationships[n.id]=3;G.toast('Lunch with '+n.name+' was lovely.');G.renderPanel('person',n.id);G.saveSilent();break;
case'applyjob':if(arg==='Junior web designer'&&s.intelligence<10){G.toast('Your intelligence needs to be 10 for that role.');break}s.job=arg;G.toast('You got the '+arg+' role. Visit the Tech Yard or use the Jobs app for shifts.');G.missionEvent('job');G.renderPanel('phone','jobs');G.saveSilent();break;
case'work':if(s.energy<18){G.toast('You need at least 18 energy to work. Rest first.');break}amount=arg==='construction'?2800:arg==='hotel'?2200:s.job==='Junior web designer'?9900:s.job==='Banker'?11600:s.job==='Musician'?7400:s.job==='Cafe assistant'?2000:2400;amount=Math.round(amount*(1+Math.min(s.jobLevel||0,4)*.12));s.energy-=18;s.cash+=amount;s.reputation++;s.shiftsCompleted=(s.shiftsCompleted||0)+1;if(s.shiftsCompleted%3===0)s.jobLevel=(s.jobLevel||0)+1;G.missionEvent('work');G.toast('Shift finished · earned '+G.money(amount)+'.');if(G.ui.panel==='phone')G.renderPanel('phone','jobs');else G.renderPanel('building',G.ui.panelTab);G.saveSilent();break;
case'deposit':el=document.getElementById('bank-amount');amount=Number(el&&el.value);if(!amount||amount<1||amount>s.cash){G.toast('Enter an amount up to your available cash.');break}s.cash-=amount;s.bank+=amount;s.bankHistory=s.bankHistory||[];s.bankHistory.unshift({label:'Cash deposit',amount,when:G.timeInfo().phoneTime});G.toast('Deposited '+G.money(amount)+'.');G.renderPanel('phone','bank');G.saveSilent();break;
case'withdraw':el=document.getElementById('bank-amount');amount=Number(el&&el.value);if(!amount||amount<1||amount>s.bank){G.toast('Enter an amount up to your bank balance.');break}s.bank-=amount;s.cash+=amount;s.bankHistory=s.bankHistory||[];s.bankHistory.unshift({label:'Cash withdrawal',amount:-amount,when:G.timeInfo().phoneTime});G.toast('Withdrew '+G.money(amount)+'.');G.renderPanel('phone','bank');G.saveSilent();break;
case'transfer':if(s.bank<500){G.toast('You need ₦500 in your bank to send a transfer.');break}s.bank-=500;s.reputation++;G.toast('₦500 sent to your closest contact.');G.renderPanel('phone','bank');G.saveSilent();break;
case'business':if(s.cash<30000){G.toast('A corner shop costs ₦30,000 to start. Pick up a few shifts first.');break}s.cash-=30000;s.business={name:'Corner Shop',stock:12,price:900,employees:0,profit:0};s.reputation+=3;G.missionEvent('upgrade');G.toast('Your Corner Shop is open!');G.renderPanel('phone','business');G.saveSilent();break;
case'businessupgrade':if(s.cash<5000){G.toast('You need ₦5,000 to restock.');break}if(!s.business){G.toast('Open a business first.');break}s.cash-=5000;s.business.stock+=10;G.toast('Shop restocked.');G.renderPanel('phone','business');G.saveSilent();break;
case'setprice':amount=Number(document.getElementById('price-amount')?.value);if(!s.business||!amount||amount<100||amount>100000){G.toast('Enter a valid price between ₦100 and ₦100,000.');break}s.business.price=amount;G.toast('Price updated to '+G.money(amount)+'.');G.renderPanel('phone','business');G.saveSilent();break;
case'hire':if(!s.business){G.toast('Open a business first.');break}if(s.business.employees>=5){G.toast('Your shop can support up to five staff.');break}if(s.cash<3000){G.toast('Hiring costs ₦3,000.');break}s.cash-=3000;s.business.employees++;G.toast('You hired a new shop assistant.');G.renderPanel('phone','business');G.saveSilent();break;case'buybike':if(s.cash<18000){G.toast('You need ₦18,000 to buy the used okada.');break}s.cash-=18000;s.vehicle={name:'Used okada',color:'#e9ac34',owned:true,bike:true};G.inventory.push('Vehicle papers: Used okada');G.missionEvent('upgrade');G.toast('You bought a used okada. Press F beside your bike to ride.');G.renderPanel('phone','vehicles');G.saveSilent();break;
case'buycar':if(s.cash<125000){G.toast('You need ₦125,000 for the Karu Compact.');break}s.cash-=125000;s.vehicle={name:'Karu Compact',color:'#c44538',owned:true};G.inventory.push('Vehicle papers: Karu Compact');G.toast('Karu Compact purchased.');G.renderPanel('phone','vehicles');G.saveSilent();break;
case'fuel':if(s.cash<2500){G.toast('You need ₦2,500 for fuel.');break}s.cash-=2500;s.fuel=100;G.missionEvent('fuel');G.toast('Tank filled.');if(G.ui.panel==='phone')G.renderPanel('phone','vehicles');else G.renderPanel('building',G.ui.panelTab);G.saveSilent();break;
case'repair':amount=Math.max(500,Math.ceil(s.carDamage*100));if(s.cash<amount){G.toast('You need '+G.money(amount)+' for repairs.');break}s.cash-=amount;s.carDamage=0;G.toast('Vehicle repaired.');G.renderPanel('building',G.ui.panelTab);G.saveSilent();break;
case'heal':if(s.cash<2000){G.toast('You need ₦2,000 for treatment.');break}s.cash-=2000;s.health=100;G.toast('Treatment complete. Health restored.');if(G.ui.panel==='phone')G.renderPanel('phone','health');else G.renderPanel('building',G.ui.panelTab);G.saveSilent();break;
case'police':amount=s.wanted*1200;if(!s.wanted){G.toast('No outstanding police matter.');break}if(s.cash<amount){G.toast('You need '+G.money(amount)+' to pay the fine.');break}s.cash-=amount;s.wanted=0;G.world.npcs=G.world.npcs.filter(x=>x.id!=='cop');G.toast('Fine paid. Wanted level cleared.');if(G.ui.panel==='phone')G.renderPanel('phone','police');else G.renderPanel('building',G.ui.panelTab);G.saveSilent();break;
case'water':if(s.cash<100){G.toast('You need ₦100.');break}s.cash-=100;s.inventory.push('Water');G.toast('Water added to your bag.');if(G.ui.panel==='phone')G.renderPanel('phone','food');else G.renderPanel('building',G.ui.panelTab);G.saveSilent();break;
case'sleep':s.energy=100;s.happiness=Math.min(100,s.happiness+20);s.hunger=Math.max(0,s.hunger-12);G.toast('You rested. Nigeria’s live clock keeps running.');G.closePanel();G.saveSilent();break;
case'upgradehome':if(s.cash<45000){G.toast('Save ₦45,000 for the estate move.');break}s.cash-=45000;s.home='Studio in Maitama Estate';s.rent=8500;G.missionEvent('upgrade');G.toast('You moved into a studio in the estate.');G.renderPanel('building',G.ui.panelTab);G.saveSilent();break;
case'gym':if(s.cash<500){G.toast('You need ₦500 for a training session.');break}if(s.energy<8){G.toast('You are too tired to train.');break}s.cash-=500;s.energy-=8;s.fitness+=3;s.happiness=Math.min(100,s.happiness+7);G.missionEvent('learn');G.toast('Training done. Fitness improved.');G.closePanel();G.saveSilent();break;
case'study':if(s.cash<700){G.toast('You need ₦700 for books and tuition.');break}s.cash-=700;s.intelligence+=2;s.energy-=7;G.missionEvent('learn');G.toast('You studied. Intelligence improved.');G.closePanel();G.saveSilent();break;
case'bus':if(s.cash<300){G.toast('You need ₦300 for the bus fare.');break}b=G.world.buildings.find(x=>x.name===arg);s.cash-=300;if(b){s.x=b.x-30;s.y=b.y+b.h+35}s.vehicle=null;G.missionEvent('travel');G.toast('You arrived at '+arg+'.');G.closePanel();G.saveSilent();break;
case'club':if(s.hour<19&&s.hour>=4){G.toast('The lounge opens at 7 PM.');break}if(s.cash<1200){G.toast('Entry costs ₦1,200.');break}s.cash-=1200;s.happiness=Math.min(100,s.happiness+12);G.toast('You danced, caught up, and enjoyed the music.');G.closePanel();G.saveSilent();break;
case'delivery':if(s.cash<1200){G.toast('You need ₦1,200 for delivery.');break}s.cash-=1200;s.inventory.push('Jollof meal');G.toast('Your jollof is on the way. Check your bag.');G.renderPanel('phone','food');G.saveSilent();break;
case'event':amount=arg==='0'?800:arg==='1'?0:500;if(s.cash<amount){G.toast('You need '+G.money(amount)+' for the ticket.');break}s.cash-=amount;s.happiness=Math.min(100,s.happiness+10);s.reputation++;G.missionEvent('rep');G.toast('You joined the city event. Good to be out.');G.renderPanel('phone','events');G.saveSilent();break;
case'movie':if(s.cash<500){G.toast('You need ₦500 for a ticket.');break}s.cash-=500;s.energy=Math.max(0,s.energy-3);s.happiness=Math.min(100,s.happiness+8);G.toast('You watched '+arg+'. A nice evening in.');G.renderPanel('phone','nollywood');G.saveSilent();break;
case'sports':if(s.sportsDate===G.timeInfo().dateKey){G.toast('You already followed today’s match.');break}s.sportsDate=G.timeInfo().dateKey;s.happiness=Math.min(100,s.happiness+3);s.reputation++;G.missionEvent('rep');G.toast('Match added to your follows. +1 reputation');G.renderPanel('phone','sports');G.saveSilent();break;
case'outfit':amount=arg==='coral'?1800:arg==='blue'?3200:0;if(s.outfit===arg){G.toast('You are already wearing that outfit.');break}if(s.cash<amount){G.toast('You need '+G.money(amount)+' for that outfit.');break}s.cash-=amount;s.outfit=arg;G.toast('Fresh look. Outfit changed.');G.renderPanel('phone','boutique');G.saveSilent();break;
case'invest':if(s.cash<5000){G.toast('You need ₦5,000 to invest.');break}s.cash-=5000;s.investments=(s.investments||0)+5000;G.toast('Savings certificate purchased. 5% yield at the next Nigeria date change.');G.renderPanel('phone','invest');G.saveSilent();break;
case'invite':n=G.world.npcs.find(x=>x.id===arg);if(!n)break;if((s.relationships[n.id]||0)<1){G.toast('Have a conversation first so they know you.');break}s.relationships[n.id]=Math.min(3,(s.relationships[n.id]||0)+1);s.happiness=Math.min(100,s.happiness+7);s.reputation++;G.missionEvent('friend');G.toast(n.name+' is coming along. Friendship grew.');G.renderPanel('phone','invite');G.saveSilent();break;
case'bill':if(s.cash<600){G.toast('You need ₦600 to pay the utility bill.');break}s.cash-=600;s.billsPaid=(s.billsPaid||0)+1;G.toast('Water and power bill paid.');G.renderPanel('phone','government');G.saveSilent();break;
case'ad':if(s.cash<1000){G.toast('You need ₦1,000 to post a city notice.');break}s.cash-=1000;s.ad=s.business?s.business.name+' · open for business':'Available for work around Abuja';s.reputation++;G.toast('Your notice is up around the city.');G.renderPanel('phone','ads');G.saveSilent();break;case'look':s.happiness=Math.min(100,s.happiness+2);G.toast('You took in the neighborhood.');G.closePanel();break;
case'load':if(G.load()){G.toast('Saved life loaded.');G.closePanel()}else G.toast('No saved life found.');break;
case'newlife':if(confirm('Start a new life? Your current local save will be removed.')){G.closePanel();document.getElementById('start-screen').classList.remove('hide')}break;}}
G.travel=function(id){let b=G.world.buildings.find(x=>x.id===id);if(!b)return;G.state.x=b.x+b.w/2;G.state.y=b.y+b.h+40;G.state.inside=null;G.closePanel();G.toast('Travelled to '+b.name+'. Walk to the entrance to go inside.');G.saveSilent()};
})();













